const { createClient } = require('@supabase/supabase-js')

const supabase = createClient(
  process.env.VITE_SUPABASE_URL,
  process.env.VITE_SUPABASE_ANON_KEY
)

// Recipes not yet in the database (cross-referenced against seed batch)
const recipes = [
  {
    title: 'Turkey/Chicken Biscuit Skillet',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '30 min',
    ingredients: [
      {amount:'1 tbsp',name:'butter'},
      {amount:'⅓ cup',name:'chopped onion'},
      {amount:'¼ cup',name:'all-purpose flour'},
      {amount:'1 can (10½ oz)',name:'condensed chicken broth, undiluted'},
      {amount:'¼ cup',name:'fat-free milk'},
      {amount:'⅛ tsp',name:'pepper'},
      {amount:'2 cups',name:'cubed cooked turkey or chicken'},
      {amount:'1 can',name:'refrigerated biscuits (or homemade)'},
      {amount:'optional',name:'mixed vegetables (peas, carrots)'},
    ],
    steps: [
      'Preheat oven to 400°F.',
      'Melt 1 tbsp butter in an oven-safe skillet over medium heat. Sauté ⅓ cup onion until softened.',
      'Whisk in ¼ cup flour, then gradually stir in the chicken broth and ¼ cup milk. Cook until thickened. Season with pepper.',
      'Stir in 2 cups cooked chicken or turkey and vegetables if using. Bring to a simmer.',
      'Arrange biscuits on top of the filling. Transfer skillet to oven and bake 15–20 minutes until biscuits are golden brown.',
    ],
    notes: null,
  },
  {
    title: 'Pizza Dough',
    category: 'Other', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Makes 3 (~10-inch) pizzas', time: '1 hr 30 min',
    ingredients: [
      {amount:'2½ cups',name:'warm (100–105°F) water'},
      {amount:'¼ cup',name:'granulated sugar'},
      {amount:'3 tsp',name:'instant yeast'},
      {amount:'¼ cup',name:'vegetable oil'},
      {amount:'5–6 cups',name:'all-purpose flour (start with 5)'},
      {amount:'2 tsp',name:'salt'},
      {amount:'as needed',name:'cornmeal or flour for dusting'},
    ],
    steps: [
      'Combine 2½ cups warm water, ¼ cup sugar, and 3 tsp yeast. Let stand 5 minutes until foamy.',
      'Add ¼ cup oil, then gradually mix in flour and 2 tsp salt until a soft dough forms. Knead 8–10 minutes until smooth and elastic.',
      'Place in an oiled bowl, cover, and rise 1 hour until doubled.',
      'Divide into 3 portions. On a floured surface, stretch or roll each portion into a 10-inch circle.',
      'Top with sauce, cheese, and toppings. Bake on a preheated pizza stone or sheet at 475°F for 10–12 minutes until crust is golden and cheese is bubbly.',
    ],
    notes: 'Makes 3 pies — freeze what you don\'t use.',
  },
  {
    title: 'Chicken Salad',
    category: 'Appetizers & Snacks', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '10 min',
    ingredients: [
      {amount:'2 cups',name:'cooked chicken (rotisserie, leftover, or 1 can Sam\'s canned chicken)'},
      {amount:'¼ cup',name:'red onion, finely chopped'},
      {amount:'2 stalks',name:'celery (including leafy tops), chopped'},
      {amount:'3–4 tbsp',name:'Miracle Whip or mayo'},
      {amount:'1 tsp',name:'Dijon mustard (optional)'},
      {amount:'to taste',name:'salt, pepper, garlic powder'},
      {amount:'optional',name:'paprika for color'},
    ],
    steps: [
      'If using canned chicken, drain and flake. If using cooked chicken, shred or chop.',
      'Combine chicken, red onion, and celery in a bowl.',
      'Stir in Miracle Whip or mayo and Dijon if using. Start with 3 tbsp and add more to taste.',
      'Season with salt, pepper, and garlic powder. Sprinkle with paprika if desired.',
      'Serve on bread, crackers, or lettuce wraps. Best if refrigerated 30 minutes before serving.',
    ],
    notes: 'Use Miracle Whip or mayo — your call.',
  },
  {
    title: 'Crock Pot Italian Roast Beef',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6–8', time: '8–10 hours',
    ingredients: [
      {amount:'3–4 lb',name:'chuck roast or round roast, trimmed'},
      {amount:'to taste',name:'kosher salt'},
      {amount:'1 can (14.5 oz)',name:'beef broth'},
      {amount:'8 oz',name:'pepperoncini pepper slices, plus ¼ cup brine'},
      {amount:'1 packet',name:'Italian dressing seasoning mix'},
      {amount:'1 tbsp',name:'Worcestershire sauce'},
      {amount:'for serving',name:'hoagie rolls, provolone cheese'},
    ],
    steps: [
      'Season roast generously with kosher salt.',
      'Place roast in slow cooker. Pour in beef broth, pepperoncini (with brine), Worcestershire, and Italian seasoning mix.',
      'Cook on low for 8–10 hours or high for 5–6 hours, until meat shreds easily with a fork.',
      'Shred beef directly in the slow cooker. Stir into the juices.',
      'Serve on toasted hoagie rolls with provolone and a ladle of au jus for dipping.',
    ],
    notes: null,
  },
  {
    title: 'Instant Pot Au Gratin Potatoes',
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6', time: '25 min',
    ingredients: [
      {amount:'2 lbs',name:'white potatoes, peeled and sliced thin (about ⅛ inch)'},
      {amount:'1 cup',name:'chicken broth'},
      {amount:'¼ cup',name:'diced onion'},
      {amount:'1 tsp',name:'dried parsley'},
      {amount:'½ tsp each',name:'garlic powder, paprika, salt'},
      {amount:'¼ tsp',name:'pepper'},
      {amount:'½ cup',name:'sour cream'},
      {amount:'1 cup',name:'shredded cheddar or Gruyère'},
      {amount:'for topping',name:'additional cheese'},
    ],
    steps: [
      'Layer sliced potatoes and onion in the Instant Pot.',
      'Mix chicken broth with garlic powder, paprika, salt, pepper, and parsley. Pour over potatoes.',
      'Seal and cook on high pressure for 5 minutes. Quick release.',
      'Stir in sour cream and half the cheese until melted and creamy.',
      'Top with remaining cheese and broil in an oven-safe dish 3–5 minutes until bubbly and golden.',
    ],
    notes: null,
  },
  {
    title: 'Tequila Lime Steak Salad',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '30 min + marinate',
    ingredients: [
      {amount:'¾ cup plus 1 tbsp',name:'lime juice, divided'},
      {amount:'¾ cup',name:'blanco tequila'},
      {amount:'2 tbsp',name:'garlic powder'},
      {amount:'1 tbsp each',name:'ground cumin, Montreal steak seasoning, dried oregano'},
      {amount:'1 tbsp',name:'olive oil'},
      {amount:'1½–2 lbs',name:'flank or skirt steak'},
      {amount:'for salad',name:'mixed greens, cherry tomatoes, red onion, avocado, corn, cotija cheese'},
      {amount:'for serving',name:'cilantro lime dressing'},
    ],
    steps: [
      'Combine all marinade ingredients. Marinate steak for at least 2 hours, up to overnight.',
      'Grill or sear steak over high heat, 3–4 minutes per side for medium-rare. Rest 5 minutes.',
      'Slice thinly against the grain.',
      'Assemble salad: greens, tomatoes, onion, avocado, corn, and cheese.',
      'Top with sliced steak and drizzle with dressing. Serve immediately.',
    ],
    notes: null,
  },
  {
    title: 'El Burrito de Roqueta',
    category: 'Other', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '45 min',
    ingredients: [
      {amount:'White American cheese, cubed',name:'for queso'},
      {amount:'1 tbsp',name:'butter'},
      {amount:'milk to thin',name:'and diced jalapeños to taste'},
      {amount:'¼ cup',name:'vegetable oil (for enchilada sauce)'},
      {amount:'2 tbsp',name:'all-purpose flour'},
      {amount:'¼ cup',name:'chili powder'},
      {amount:'1 tsp each',name:'garlic powder, cumin, oregano, salt'},
      {amount:'¼ tsp',name:'black pepper'},
      {amount:'2 cups',name:'chicken or vegetable broth'},
      {amount:'for filling',name:'seasoned meat, rice, beans, cheese, sour cream'},
    ],
    steps: [
      'Make queso: Melt butter in a saucepan. Add cubed white American cheese and melt over low heat with a splash of milk. Stir in jalapeños. Keep warm.',
      'Make enchilada sauce: Heat oil in a saucepan. Whisk in flour, cook 1 minute. Add all dry spices. Slowly whisk in broth. Simmer until thickened, 5–10 minutes.',
      'Build burritos with your choice of fillings: seasoned meat, rice, beans, cheese, sour cream.',
      'Drizzle enchilada sauce over assembled burritos and top with queso.',
      'Optional: bake at 375°F for 10 minutes until the sauce is bubbly.',
    ],
    notes: 'Start with homemade enchilada sauce and queso — makes all the difference.',
  },
  {
    title: 'Voodoo Chicken',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '1 hour',
    ingredients: [
      {amount:'1 tsp each',name:'salt, filé powder, oregano, dried onion, black pepper, cayenne, garlic powder, ground thyme'},
      {amount:'4',name:'bay leaves'},
      {amount:'to taste',name:'Cajun or Creole seasoning (Slap Ya Mama recommended)'},
      {amount:'3–4 lbs',name:'bone-in chicken pieces'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'1 can',name:'diced tomatoes'},
      {amount:'1',name:'bell pepper, sliced'},
      {amount:'1',name:'onion, sliced'},
      {amount:'for serving',name:'cooked rice or crusty bread'},
    ],
    steps: [
      'Combine all spices and Cajun seasoning. Coat chicken pieces generously in the rub.',
      'Heat olive oil in a Dutch oven over medium-high. Sear chicken skin-side down until golden, 4–5 minutes per side. Remove.',
      'In the same pot, sauté onion and bell pepper 3–4 minutes. Add diced tomatoes with their juices.',
      'Return chicken to the pot. Cover and cook over medium-low for 35–45 minutes until chicken is tender and cooked through.',
      'Remove bay leaves. Serve over rice with pan juices spooned over the top.',
    ],
    notes: 'Add Slap Ya Mama or any good Cajun seasoning to taste.',
  },
  {
    title: 'Moroccan-Style Roasted Vegetables',
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '40 min',
    ingredients: [
      {amount:'5 tbsp',name:'extra-virgin olive oil'},
      {amount:'juice of ½',name:'small lemon'},
      {amount:'2 large cloves',name:'garlic, minced'},
      {amount:'1 large',name:'white onion, diced'},
      {amount:'1–2 medium',name:'zucchini, cubed'},
      {amount:'1',name:'red bell pepper, cubed'},
      {amount:'1 can',name:'chickpeas, drained'},
      {amount:'1 tsp each',name:'cumin, coriander, paprika, turmeric'},
      {amount:'½ tsp',name:'cinnamon'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'for garnish',name:'fresh cilantro or parsley'},
    ],
    steps: [
      'Preheat oven to 425°F. Line a large baking sheet with foil and spray with cooking spray.',
      'Whisk olive oil, lemon juice, garlic, and all spices together in a large bowl.',
      'Toss all vegetables and chickpeas in the spiced oil mixture until well coated.',
      'Spread in a single layer on the baking sheet. Roast 25–30 minutes, tossing halfway, until tender and caramelized.',
      'Garnish with fresh cilantro or parsley. Serve over couscous or as a side.',
    ],
    notes: null,
  },
  {
    title: 'Chicken Bacon Ranch Quesadillas',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '25 min',
    ingredients: [
      {amount:'4 large',name:'flour tortillas'},
      {amount:'2 cups',name:'shredded Mexican blend and mozzarella cheese, mixed'},
      {amount:'to taste',name:'ranch dressing'},
      {amount:'2 cups',name:'cooked chicken, shredded or diced'},
      {amount:'6 strips',name:'bacon, cooked and crumbled'},
      {amount:'to taste',name:'ranch seasoning, garlic powder, salt and pepper'},
      {amount:'as needed',name:'butter or oil for cooking'},
    ],
    steps: [
      'Season chicken with ranch seasoning, garlic powder, salt, and pepper while cooking if using raw.',
      'Lay a tortilla flat. Spread a thin layer of ranch dressing on one half.',
      'Top with shredded chicken, crumbled bacon, and a generous amount of mixed cheeses.',
      'Fold tortilla in half. Cook in a buttered skillet over medium heat, 2–3 minutes per side until golden and cheese is melted.',
      'Slice into wedges and serve with extra ranch for dipping.',
    ],
    notes: null,
  },
  {
    title: 'Cinnamon Roll Cake',
    category: 'Desserts', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 12', time: '40 min',
    ingredients: [
      {amount:'1½ cups',name:'all-purpose flour'},
      {amount:'½ cup',name:'granulated sugar'},
      {amount:'2 tsp',name:'baking powder'},
      {amount:'¼ tsp',name:'salt'},
      {amount:'¾ cup',name:'milk'},
      {amount:'1',name:'large egg'},
      {amount:'1 tsp',name:'vanilla extract'},
      {amount:'¼ cup',name:'butter, melted'},
      {amount:'Filling: ⅓ cup butter softened',name:'½ cup brown sugar packed, 1 tbsp cinnamon'},
      {amount:'Glaze: 1 cup powdered sugar',name:'2–3 tbsp milk, ½ tsp vanilla'},
    ],
    steps: [
      'Preheat oven to 350°F. Grease a 9x9 baking pan.',
      'Whisk flour, sugar, baking powder, and salt. Mix in milk, egg, vanilla, and melted butter until smooth. Pour into pan.',
      'Mix softened butter, brown sugar, and cinnamon. Drop by spoonfuls over the batter, then swirl through with a knife.',
      'Bake 25–30 minutes until a toothpick comes out clean.',
      'While warm, drizzle with glaze (whisk powdered sugar, milk, and vanilla). Serve warm.',
    ],
    notes: 'All the flavors of a cinnamon roll in an easy pour-and-bake cake.',
  },
  {
    title: 'Lemon Shrimp & Rice',
    category: 'Seafood', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '25 min',
    ingredients: [
      {amount:'12 oz',name:'shrimp (41–60 count), peeled and deveined'},
      {amount:'juice and zest of 1',name:'fresh lemon'},
      {amount:'4 cloves',name:'garlic, minced'},
      {amount:'2 tbsp',name:'butter'},
      {amount:'1½ cups',name:'long-grain white rice'},
      {amount:'2 cups',name:'chicken broth'},
      {amount:'½ cup',name:'water'},
      {amount:'to taste',name:'salt, pepper, red pepper flakes'},
      {amount:'for garnish',name:'fresh parsley'},
    ],
    steps: [
      'Cook rice in chicken broth and ½ cup water per package directions. Set aside.',
      'In a large skillet, melt 2 tbsp butter over medium-high. Add garlic and cook 30 seconds.',
      'Add shrimp. Cook 1–2 minutes per side until pink and cooked through.',
      'Add lemon juice, lemon zest, and red pepper flakes. Toss to coat. Season with salt and pepper.',
      'Serve shrimp over rice. Garnish with fresh parsley.',
    ],
    notes: 'Budget-friendly one-pan meal with bright lemon flavor.',
  },
  {
    title: 'Sausage, Peppers & Onions',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '35 min',
    ingredients: [
      {amount:'to taste',name:'fresh Italian sausage links (sweet or hot)'},
      {amount:'1 each',name:'white and red onion, sliced'},
      {amount:'3 colors',name:'bell peppers (red, yellow, orange), sliced'},
      {amount:'3–4 cloves',name:'garlic, sliced'},
      {amount:'as needed',name:'olive oil'},
      {amount:'to taste',name:'salt, pepper, red pepper flakes'},
      {amount:'¼ cup',name:'apple cider or apple cider vinegar'},
      {amount:'for serving',name:'hoagie rolls or pasta'},
    ],
    steps: [
      'Heat olive oil in a large skillet over medium-high. Brown sausage links on all sides, about 5 minutes. Remove and slice on the bias.',
      'Add a little more oil to the pan. Sauté onions and peppers until softened and starting to caramelize, 8–10 minutes.',
      'Add garlic. Cook 1 minute. Season with salt, pepper, and red pepper flakes.',
      'Return sliced sausage to the pan. Add apple cider. Cook 3–5 minutes until liquid reduces and everything is well coated.',
      'Serve in hoagie rolls or over pasta.',
    ],
    notes: null,
  },
  {
    title: 'Baked Rigatoni',
    category: 'Pasta', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6', time: '50 min',
    ingredients: [
      {amount:'1 jar (24 oz)',name:'marinara sauce'},
      {amount:'3 cups',name:'beef broth'},
      {amount:'¼ cup',name:'tomato paste'},
      {amount:'4 cloves',name:'garlic, grated'},
      {amount:'to taste',name:'kosher salt and black pepper'},
      {amount:'1 lb',name:'ground beef or Italian sausage'},
      {amount:'1 lb',name:'rigatoni, cooked al dente'},
      {amount:'2 cups',name:'shredded mozzarella'},
      {amount:'½ cup',name:'Parmesan'},
      {amount:'for garnish',name:'fresh basil'},
    ],
    steps: [
      'Brown meat in a large pot. Drain fat. Add garlic, tomato paste, marinara, and beef broth. Simmer 20 minutes.',
      'Preheat oven to 375°F. Butter a large baking dish.',
      'Toss cooked rigatoni with the meat sauce. Pour into the baking dish.',
      'Top with mozzarella and Parmesan.',
      'Bake 25–30 minutes until bubbly and cheese is golden. Garnish with fresh basil.',
    ],
    notes: null,
  },
  {
    title: 'Smoked Pork Loin',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6–8', time: '3–4 hours',
    ingredients: [
      {amount:'2',name:'pork tenderloins (~1–1½ lb each), or 1 larger pork loin (2 lbs)'},
      {amount:'Option A rub: ½ tsp paprika',name:'1 tbsp each: brown sugar, kosher salt, garlic powder'},
      {amount:'½ tbsp',name:'fresh-ground black pepper'},
      {amount:'1 tsp each',name:'onion powder, dried thyme'},
      {amount:'Option B marinade',name:'cherry cider (enough to marinate 4–6 hours)'},
      {amount:'as needed',name:'cherry wood chips for smoking'},
    ],
    steps: [
      'Trim excess fat from pork loin. Option A: score fat cap in ¼-inch diagonal cuts and apply dry rub generously.',
      'Option B: Marinate in cherry cider for at least 4–6 hours in the refrigerator.',
      'Preheat smoker to 225–250°F. Use cherry wood for smoke.',
      'Smoke until internal temperature reaches 145°F, about 2–3 hours depending on size.',
      'Rest 10 minutes before slicing. Serve with sides of your choice.',
    ],
    notes: 'Two versions: dry rub or cherry cider marinade. Both are great.',
  },
  {
    title: 'Instant Pot Chicken & Rice',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '30 min',
    ingredients: [
      {amount:'1½ cups',name:'long-grain basmati rice'},
      {amount:'2 cups',name:'chicken stock'},
      {amount:'1 tbsp',name:'oil'},
      {amount:'2 tbsp',name:'butter'},
      {amount:'1 large',name:'onion, diced'},
      {amount:'1½ tbsp',name:'garlic, minced'},
      {amount:'1½ tbsp',name:'mixed herbs (oregano, thyme, parsley)'},
      {amount:'½ tsp',name:'chili powder'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'2–3',name:'boneless skinless chicken breasts or thighs'},
    ],
    steps: [
      'Set Instant Pot to Sauté. Heat oil and butter. Cook onion until softened, 4–5 minutes. Add garlic and herbs; cook 1 minute.',
      'Season chicken with chili powder, salt, and pepper. Add to pot and sear each side 2 minutes.',
      'Add rice and chicken stock. Stir to combine. Make sure nothing is stuck to the bottom.',
      'Seal lid. Cook on high pressure for 10 minutes. Natural release for 10 minutes, then quick release.',
      'Fluff rice with a fork. Slice or shred chicken. Serve together with a squeeze of lemon if desired.',
    ],
    notes: null,
  },
  {
    title: 'BBQ Pulled Pork Pop Tarts',
    category: 'Appetizers & Snacks', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6', time: '45 min',
    ingredients: [
      {amount:'2 tbsp',name:'unsalted butter'},
      {amount:'1',name:'yellow onion, thinly sliced'},
      {amount:'½ tsp',name:'light brown sugar'},
      {amount:'2 cups',name:'cooked pulled pork'},
      {amount:'¼ cup',name:'BBQ sauce'},
      {amount:'2 sheets',name:'puff pastry, thawed'},
      {amount:'1 egg + 1 tbsp water',name:'egg wash'},
      {amount:'for serving',name:'additional BBQ sauce'},
    ],
    steps: [
      'Melt butter in a skillet over medium. Cook sliced onion with brown sugar until deeply caramelized, 20–25 minutes. Let cool.',
      'Mix pulled pork with BBQ sauce and caramelized onions.',
      'Preheat oven to 400°F. Cut puff pastry into ~3x4 inch rectangles.',
      'Place a spoonful of pork filling on half the rectangles, leaving a border. Top with a matching pastry rectangle and press edges with a fork to seal. Cut 2–3 small vents. Brush with egg wash.',
      'Bake 20–25 minutes until puffed and golden. Serve with extra BBQ sauce for dipping.',
    ],
    notes: 'Perfect for game day or a fun dinner.',
  },
  {
    title: 'Baked Tilapia',
    category: 'Seafood', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6', time: '25 min',
    ingredients: [
      {amount:'6',name:'tilapia fillets'},
      {amount:'¼ cup',name:'extra-virgin olive oil'},
      {amount:'4 sprigs',name:'fresh thyme'},
      {amount:'3',name:'tomatoes, peeled, seeded, and chopped'},
      {amount:'½ cup',name:'coarsely chopped green olives'},
      {amount:'¼ tsp',name:'dried hot red pepper flakes'},
      {amount:'2',name:'garlic cloves, minced'},
      {amount:'to taste',name:'salt and black pepper'},
      {amount:'for serving',name:'lemon wedges'},
    ],
    steps: [
      'Preheat oven to 400°F.',
      'Arrange tilapia in a single layer in a greased baking dish. Season with salt and pepper.',
      'In a small bowl, combine olive oil, thyme, tomatoes, olives, garlic, and red pepper flakes.',
      'Spoon mixture evenly over the fish.',
      'Bake 15–20 minutes until fish is opaque and flakes easily with a fork. Serve with lemon wedges.',
    ],
    notes: 'Mediterranean-style baked tilapia.',
  },
  {
    title: 'Steak & Broccoli Stir Fry',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '25 min',
    ingredients: [
      {amount:'1 tbsp',name:'olive oil, divided'},
      {amount:'1½ lbs',name:'flank steak, very thinly sliced across the grain'},
      {amount:'3 cloves',name:'garlic, minced'},
      {amount:'1',name:'shallot, finely chopped'},
      {amount:'4',name:'green onions, thinly sliced'},
      {amount:'4 cups',name:'broccoli florets'},
      {amount:'Sauce: 3 tbsp soy sauce',name:'2 tbsp oyster sauce, 1 tbsp sesame oil, 1 tsp brown sugar, 1 tsp cornstarch, ½ tsp red pepper flakes'},
      {amount:'for serving',name:'cooked rice'},
    ],
    steps: [
      'Whisk together all sauce ingredients. Set aside.',
      'Heat ½ tbsp oil in a wok or large skillet over very high heat. Sear steak strips in a single layer, 60–90 seconds per side until browned. Work in batches. Remove steak.',
      'Add remaining oil. Stir-fry broccoli 2 minutes. Add garlic and shallot; cook 30 seconds.',
      'Pour sauce over broccoli. Toss and cook 1 minute until slightly thickened.',
      'Return steak to pan. Add green onions. Toss everything together and serve immediately over rice.',
    ],
    notes: 'Very high heat and not overcrowding the pan are the keys.',
  },
  {
    title: 'Ham & BBQ Bean Crock Pot',
    category: 'Soups & Stews', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 8', time: '8–10 hours',
    ingredients: [
      {amount:'1 lb',name:'dried navy beans, soaked overnight'},
      {amount:'1 small',name:'onion, finely chopped'},
      {amount:'½ cup',name:'ketchup'},
      {amount:'¼ cup',name:'maple syrup'},
      {amount:'¼ cup',name:'packed dark brown sugar'},
      {amount:'2 tbsp',name:'yellow mustard'},
      {amount:'1½ tbsp',name:'Worcestershire sauce'},
      {amount:'ham hock or 1–2 cups',name:'cubed cooked ham'},
      {amount:'1 tsp',name:'smoked paprika'},
      {amount:'to taste',name:'salt and pepper'},
    ],
    steps: [
      'Soak dried beans overnight in water. Drain and rinse.',
      'Place beans in slow cooker. Add onion, ham, and enough water to cover by 2 inches.',
      'Stir in ketchup, maple syrup, brown sugar, mustard, Worcestershire, and paprika.',
      'Cook on low for 8–10 hours until beans are very tender. Add water as needed throughout.',
      'Season with salt and pepper. Serve as a side dish or over cornbread.',
    ],
    notes: 'Old-school barbecue baked beans. Perfect for cookouts.',
  },
  {
    title: 'Crock Pot Flank Steak',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '6–8 hours',
    ingredients: [
      {amount:'1½–2 lbs',name:'flank steak'},
      {amount:'1 can (15 oz)',name:'crushed tomatoes'},
      {amount:'3 tbsp',name:'ketchup'},
      {amount:'1 tbsp',name:'apple cider vinegar'},
      {amount:'2 cloves',name:'garlic, minced'},
      {amount:'1½ tsp',name:'ground cumin'},
      {amount:'1',name:'jalapeño pepper, thinly sliced (with seeds)'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'for serving',name:'rice or tortillas'},
    ],
    steps: [
      'Season flank steak with salt and pepper.',
      'Combine crushed tomatoes, ketchup, apple cider vinegar, garlic, cumin, and jalapeño in the slow cooker.',
      'Add steak, turning to coat in the sauce.',
      'Cook on low for 6–8 hours or high for 4–5 hours until very tender.',
      'Shred or slice the meat and stir into the sauce. Serve over rice or in tortillas.',
    ],
    notes: 'Great for tacos or served over rice.',
  },
  {
    title: 'Crock Pot Italian Herb Chicken',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '6–7 hours',
    ingredients: [
      {amount:'4',name:'boneless skinless chicken breasts (or 4–6 thighs)'},
      {amount:'3 cups',name:'chopped potatoes (about 1½-inch pieces)'},
      {amount:'3 tbsp',name:'oil'},
      {amount:'1 tbsp',name:'Italian seasoning blend'},
      {amount:'1 tsp',name:'garlic powder'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'½ cup',name:'chicken broth'},
      {amount:'for serving',name:'Parmesan and parsley'},
    ],
    steps: [
      'Toss potatoes with oil, Italian seasoning, garlic powder, salt, and pepper.',
      'Place chicken in the slow cooker. Surround with seasoned potatoes.',
      'Pour chicken broth over everything.',
      'Cook on low for 6–7 hours or high for 3–4 hours, until chicken is cooked through and potatoes are tender.',
      'Serve sprinkled with Parmesan and fresh parsley.',
    ],
    notes: 'Effortless weeknight go-to.',
  },
  {
    title: 'Pork Loin Roast',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6–8', time: '4–6 hours marinate + 80 min roast',
    ingredients: [
      {amount:'¼ cup',name:'reduced-sodium soy sauce'},
      {amount:'6',name:'garlic cloves, minced'},
      {amount:'1 tbsp each',name:'minced fresh basil, rosemary, and sage'},
      {amount:'1 tbsp',name:'ground mustard'},
      {amount:'1',name:'pork loin roast (3½ lbs)'},
      {amount:'1 cup',name:'water'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'for serving',name:'roasted vegetables'},
    ],
    steps: [
      'Combine soy sauce, garlic, herbs, and mustard. Rub all over the pork loin.',
      'Place in a zip-lock bag or covered dish. Marinate in refrigerator at least 4 hours, preferably overnight.',
      'Preheat oven to 350°F. Place pork in a roasting pan. Add water to the bottom of the pan.',
      'Roast uncovered for 60–80 minutes until internal temperature reaches 145°F.',
      'Rest 10–15 minutes before slicing. Use pan drippings for a simple au jus.',
    ],
    notes: 'An herb and soy-marinated pork loin roast. Impressive for a Sunday dinner.',
  },
  {
    title: 'Crock Pot Chicken Marsala & Garlic Mashed Potatoes',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6', time: '4–6 hours',
    ingredients: [
      {amount:'6',name:'boneless skinless chicken breasts'},
      {amount:'1 tbsp',name:'olive oil'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'2 tsp',name:'minced garlic'},
      {amount:'½ cup',name:'Marsala wine'},
      {amount:'½ cup',name:'chicken broth'},
      {amount:'¼ cup',name:'cornstarch'},
      {amount:'¼ cup',name:'heavy cream'},
      {amount:'8 oz',name:'cremini mushrooms, sliced'},
      {amount:'2 lbs potatoes',name:'boiled and mashed with butter, cream, roasted garlic, salt and pepper'},
    ],
    steps: [
      'Season chicken with salt and pepper. Brown briefly in olive oil in a skillet for color.',
      'Add chicken to slow cooker. Add garlic, Marsala, chicken broth, and mushrooms.',
      'Cook on low for 4–6 hours or high for 2–3 hours until chicken is cooked through.',
      'Mix cornstarch with a little cold water and stir into slow cooker with heavy cream. Cook on high 20–30 minutes until sauce thickens.',
      'Make garlic mashed potatoes: mash boiled potatoes with butter, cream, roasted garlic, salt, and pepper. Serve chicken and sauce over mashed potatoes.',
    ],
    notes: 'A set-it-and-forget-it version of the classic.',
  },
  {
    title: 'Slow Cooker Ham and Potatoes',
    category: 'Soups & Stews', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 8', time: '6–8 hours',
    ingredients: [
      {amount:'8 cups',name:'russet potatoes, diced'},
      {amount:'1',name:'yellow onion, diced'},
      {amount:'2 large',name:'carrots, peeled and chopped'},
      {amount:'½ cup',name:'celery, chopped'},
      {amount:'16 oz',name:'ham, cubed'},
      {amount:'1 tsp',name:'kosher salt'},
      {amount:'¼ tsp',name:'coarse black pepper'},
      {amount:'2 cups',name:'chicken broth'},
      {amount:'1 cup',name:'heavy cream or half-and-half'},
      {amount:'for serving',name:'shredded cheddar and sour cream'},
    ],
    steps: [
      'Place potatoes, onion, carrots, celery, and ham in the slow cooker.',
      'Pour chicken broth over everything. Season with salt and pepper.',
      'Cook on low 6–8 hours or high 3–4 hours until potatoes and carrots are tender.',
      'Stir in heavy cream and cook on high for 20 more minutes.',
      'Serve topped with shredded cheddar and a dollop of sour cream.',
    ],
    notes: null,
  },
  {
    title: 'Instant Pot Mashed Potatoes',
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6–8', time: '20 min',
    ingredients: [
      {amount:'2½ lbs',name:'Russet or Yukon gold potatoes, peeled and quartered'},
      {amount:'1 tsp',name:'salt'},
      {amount:'½ cup',name:'sour cream'},
      {amount:'¼ cup',name:'butter, softened'},
      {amount:'2 oz',name:'cream cheese, softened'},
      {amount:'1',name:'garlic clove, minced'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'as needed',name:'milk to adjust consistency'},
    ],
    steps: [
      'Add potatoes and 1 tsp salt to Instant Pot. Add enough water to just cover. Cook on high pressure for 10 minutes. Quick release.',
      'Drain water. Return potatoes to pot.',
      'Add butter, cream cheese, sour cream, and garlic. Mash until smooth.',
      'Add a splash of milk if needed to reach desired consistency.',
      'Season with salt and pepper. Serve hot.',
    ],
    notes: 'Perfectly creamy mashed potatoes in under 20 minutes.',
  },
  {
    title: 'Crock Pot Sausage Stuffing',
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 10–12', time: '3–4 hours',
    ingredients: [
      {amount:'12 cups',name:'bread cubes'},
      {amount:'2½–3 cups',name:'chicken stock'},
      {amount:'3 large',name:'eggs, well beaten'},
      {amount:'3 tbsp',name:'butter'},
      {amount:'2½–3 cups',name:'chopped celery'},
      {amount:'1½ cups',name:'chopped onions'},
      {amount:'1 tbsp',name:'minced garlic'},
      {amount:'½ lb',name:'hot sausage, browned and crumbled'},
      {amount:'to taste',name:'salt, pepper, poultry seasoning'},
      {amount:'to taste',name:'fresh or dried sage, thyme, parsley'},
    ],
    steps: [
      'Brown sausage in a skillet, breaking into crumbles. Drain excess fat.',
      'In the same skillet, sauté celery, onion, and garlic in butter until softened.',
      'Combine bread cubes, sausage, sautéed vegetables, and all seasonings in the slow cooker.',
      'Whisk eggs into chicken stock, then pour over bread mixture. Toss gently — bread should be moist but not soggy.',
      'Cook on low for 3–4 hours, stirring once halfway through. Done when set and lightly browned on edges.',
    ],
    notes: 'A hearty holiday stuffing made right in the slow cooker.',
  },
  {
    title: 'Snoop Dogg Turkey',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 10–12', time: '3–4 hours + overnight brine',
    ingredients: [
      {amount:'1',name:'whole turkey (12–14 lbs), thawed'},
      {amount:'¼ cup',name:'kosher salt'},
      {amount:'2 medium',name:'oranges'},
      {amount:'1 package',name:'fresh poultry herbs (sage, thyme, rosemary)'},
      {amount:'½ cup',name:'butter, softened'},
      {amount:'6 cloves',name:'garlic, minced'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'to taste',name:'black pepper'},
      {amount:'as needed',name:'chicken broth for basting'},
    ],
    steps: [
      'The day before: pat turkey dry. Rub kosher salt all over, including under the skin. Refrigerate uncovered overnight.',
      'Remove turkey from fridge 1 hour before cooking. Preheat oven to 325°F.',
      'Mix softened butter with garlic and chopped fresh herbs. Rub herb butter under and over the skin.',
      'Stuff cavity with halved oranges and remaining herb sprigs. Truss legs if desired.',
      'Roast on a rack, basting with pan drippings every 45 minutes. Roast until internal temp in the thigh reaches 165°F — approximately 13–15 min per pound. Tent with foil if browning too quickly. Rest 30 minutes before carving.',
    ],
    notes: 'A perfectly seasoned herb-rubbed whole turkey.',
  },
  {
    title: 'Bacon Cheese Tortellini',
    category: 'Pasta', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6', time: '30 min',
    ingredients: [
      {amount:'8 oz',name:'shredded cheddar'},
      {amount:'1 lb',name:'bacon, cooked and crumbled'},
      {amount:'1',name:'rotisserie chicken, shredded'},
      {amount:'¾ cup',name:'chicken broth'},
      {amount:'1½ cups',name:'heavy cream'},
      {amount:'¼ cup',name:'ranch dressing'},
      {amount:'2 tbsp',name:'ranch seasoning'},
      {amount:'1½ tsp',name:'black pepper'},
      {amount:'1 tsp',name:'garlic powder'},
      {amount:'24 oz',name:'cheese tortellini, cooked'},
    ],
    steps: [
      'Cook tortellini according to package directions. Drain and set aside.',
      'In a large skillet, combine chicken broth, heavy cream, ranch dressing, and ranch seasoning. Bring to a simmer.',
      'Stir in shredded cheddar, pepper, and garlic powder until cheese melts and sauce is smooth.',
      'Add shredded chicken, crumbled bacon, and cooked tortellini. Toss to coat.',
      'Serve hot. Top with extra bacon and cheese if desired.',
    ],
    notes: 'A crowd-pleasing pasta.',
  },
  {
    title: 'Slow Cooker Loaded Chicken and Potatoes',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 8', time: '6–7 hours',
    ingredients: [
      {amount:'½ cup',name:'chicken broth'},
      {amount:'3½ tbsp',name:'ranch dressing mix'},
      {amount:'2 lbs',name:'boneless, skinless chicken breasts'},
      {amount:'1½ lbs',name:'yellow baby new potatoes'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'6 slices',name:'bacon, cooked and crumbled'},
      {amount:'1 cup',name:'shredded cheddar'},
      {amount:'for serving',name:'sour cream and green onions'},
    ],
    steps: [
      'Add chicken broth and ranch mix to the slow cooker and stir.',
      'Toss potatoes with olive oil, salt, and pepper. Add to the slow cooker.',
      'Nestle chicken breasts on top. Cook on low 6–7 hours or high 3–4 hours until chicken is cooked through.',
      'Shred chicken with two forks right in the pot.',
      'Top servings with crumbled bacon, shredded cheddar, and sour cream. Garnish with green onions.',
    ],
    notes: 'Ranch-seasoned chicken and baby potatoes loaded with bacon and cheese.',
  },
  {
    title: 'Crockpot Cheesy Potatoes',
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 8–10', time: '4–5 hours',
    ingredients: [
      {amount:'28 oz bag',name:'frozen diced hashbrowns'},
      {amount:'1 can',name:'cream of chicken soup'},
      {amount:'16 oz',name:'Colby Jack cheese, shredded'},
      {amount:'4 oz',name:'sharp cheddar, shredded'},
      {amount:'8 oz',name:'French onion dip'},
      {amount:'to taste',name:'salt, pepper, and garlic powder'},
      {amount:'optional',name:'crushed Ritz crackers for topping'},
    ],
    steps: [
      'Combine frozen hashbrowns, cream of chicken soup, French onion dip, and shredded cheeses in the slow cooker.',
      'Season with salt, pepper, and garlic powder. Stir to combine.',
      'Cook on low for 4–5 hours or high for 2–3 hours, stirring once or twice.',
      'Optional: top with crushed crackers tossed in melted butter in the last 30 minutes.',
      'Serve hot as a side dish.',
    ],
    notes: 'The ultimate potluck side dish. Shred your own cheese for best melt.',
  },
  {
    title: 'Crunchy Cheesy Potatoes',
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 8–10', time: '55 min',
    ingredients: [
      {amount:'1 bag (2 lb)',name:'frozen cubed or shredded hashbrowns'},
      {amount:'2 cups',name:'sour cream'},
      {amount:'2 cups',name:'shredded sharp cheddar'},
      {amount:'1 can (10.5 oz)',name:'cream of chicken soup'},
      {amount:'½ cup',name:'butter, melted'},
      {amount:'to taste',name:'salt, pepper, garlic powder'},
      {amount:'for topping',name:'cornflake or crushed cracker topping with melted butter'},
    ],
    steps: [
      'Preheat oven to 350°F. Grease a 9x13 baking dish.',
      'In a large bowl, mix hashbrowns, sour cream, shredded cheese, cream of chicken soup, and melted butter. Season with salt, pepper, and garlic powder.',
      'Spread evenly in the baking dish.',
      'Top with crushed cornflakes or crackers tossed in melted butter.',
      'Bake 45–55 minutes until bubbly and topping is golden and crunchy.',
    ],
    notes: 'A potluck legend.',
  },
  {
    title: 'Crockpot Salisbury Steak',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '6–8 hours',
    ingredients: [
      {amount:'4–6',name:'frozen Angus hamburger patties'},
      {amount:'½–1 whole',name:'onion, fajita-sliced'},
      {amount:'1 can',name:'cream of onion soup'},
      {amount:'1 can',name:'beef consommé'},
      {amount:'1 package',name:'Lipton Beefy Onion soup mix'},
      {amount:'2',name:'garlic cloves, chopped'},
      {amount:'several splashes',name:'Worcestershire sauce'},
      {amount:'a few tbsp',name:'ketchup'},
      {amount:'for serving',name:'mashed potatoes or egg noodles'},
    ],
    steps: [
      'Place frozen patties in the bottom of the slow cooker. Layer sliced onions on top.',
      'Whisk together cream of onion soup, beef consommé, Lipton soup mix, garlic, Worcestershire, and ketchup. Pour over patties.',
      'Cook on low for 6–8 hours or high for 3–4 hours.',
      'Serve over mashed potatoes or egg noodles with plenty of gravy spooned over top.',
    ],
    notes: 'Comfort food classic — no fuss, big flavor.',
  },
  {
    title: 'Meatball Subs',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '40 min',
    ingredients: [
      {amount:'1 lb',name:'ground beef'},
      {amount:'¾ cup',name:'bread crumbs'},
      {amount:'1 large',name:'egg, beaten'},
      {amount:'2 cloves',name:'garlic, minced'},
      {amount:'2 tbsp each',name:'grated Parmesan, Worcestershire sauce'},
      {amount:'1 tsp',name:'Italian seasoning'},
      {amount:'½ tsp each',name:'salt, black pepper'},
      {amount:'1 jar',name:'marinara sauce'},
      {amount:'for serving',name:'hoagie rolls, shredded mozzarella or provolone'},
    ],
    steps: [
      'Mix all meatball ingredients together. Form into 1½-inch balls.',
      'Brown meatballs in a skillet over medium-high heat on all sides, then transfer to a pot with marinara sauce.',
      'Simmer in sauce for 20 minutes until cooked through.',
      'Toast hoagie rolls. Pile on meatballs and sauce. Top with cheese.',
      'Broil subs for 2–3 minutes until cheese is bubbly and golden. Serve hot.',
    ],
    notes: null,
  },
  {
    title: 'Crockpot Orange Chicken',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '3–4 hours',
    ingredients: [
      {amount:'3–4',name:'chicken breasts, cubed'},
      {amount:'1 cup',name:'BBQ sauce'},
      {amount:'¾ cup',name:'orange marmalade'},
      {amount:'2 tbsp',name:'reduced-sodium soy sauce'},
      {amount:'for serving',name:'fresh-cooked rice'},
    ],
    steps: [
      'Cube chicken and place in the slow cooker on high for 1½ hours (or low for 3 hours).',
      'Mix BBQ sauce, orange marmalade, and soy sauce. Pour over chicken.',
      'Cook on high 1½–2 more hours until chicken is cooked through and sauce is thickened.',
      'Shred or leave cubed. Serve hot over rice.',
    ],
    notes: 'Updated version adds soy sauce for depth.',
  },
  {
    title: 'Crock Pot Chicken Wings',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '4–5 hours + broil',
    ingredients: [
      {amount:'3–4 lbs',name:'chicken wings (frozen is fine)'},
      {amount:'¼ cup',name:'brown sugar'},
      {amount:'1 cup',name:'diced onion'},
      {amount:'as desired',name:'favorite wing sauce (Buffalo, BBQ, etc.)'},
    ],
    steps: [
      'Put chicken wings in the slow cooker. Pour brown sugar and diced onion on top.',
      'Add wing sauce over the top.',
      'Cook on low 4–5 hours or high 2–3 hours.',
      'Transfer wings to a foil-lined baking sheet and broil 5–7 minutes per side for crispy skin.',
      'Toss in additional sauce and serve.',
    ],
    notes: 'Let the slow cooker do the work — finish under the broiler for crispy skin.',
  },
]

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  if (req.headers['x-seed-secret'] !== process.env.SEED_SECRET) return res.status(401).json({ error: 'Unauthorized' })

  try {
    const batchSize = 10
    let inserted = 0
    for (let i = 0; i < recipes.length; i += batchSize) {
      const batch = recipes.slice(i, i + batchSize)
      const { data, error } = await supabase.from('recipes').insert(batch).select()
      if (error) throw error
      inserted += data.length
    }
    return res.status(200).json({ success: true, inserted })
  } catch (err) {
    return res.status(500).json({ error: err.message })
  }
}
