const { createClient } = require('@supabase/supabase-js')

const supabase = createClient(
  process.env.VITE_SUPABASE_URL,
  process.env.VITE_SUPABASE_ANON_KEY
)

const recipes = [
  {
    title: 'Lollipop Drumsticks',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '45 min',
    ingredients: [
      {amount:'10–12',name:'chicken drumsticks'},
      {amount:'10–12 strips',name:'thick-cut bacon'},
      {amount:'2 tbsp',name:'neutral oil or melted ghee'},
      {amount:'2 tbsp',name:'all-purpose or sweet heat seasoning rub'},
      {amount:'1 tsp each',name:'garlic powder, onion powder, smoked paprika'},
      {amount:'for finishing',name:'BBQ glaze or sauce'},
    ],
    steps: [
      'Push the meat down each drumstick to form a lollipop shape, exposing the bone.',
      'Wrap each drumstick with a strip of bacon and secure with a toothpick.',
      'Brush with oil or ghee, then season all over with rub, garlic powder, onion powder, and paprika.',
      'Cook at 375°F (oven or grill) for 35–45 minutes, turning halfway, until bacon is crispy and chicken reaches 165°F internally.',
      'Brush with BBQ glaze in the last 5–10 minutes. Serve hot.',
    ],
    notes: null,
  },
  {
    title: 'Crockpot Chicken Tacos',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 6', time: '6–8 hours',
    ingredients: [
      {amount:'4',name:'boneless skinless chicken breasts'},
      {amount:'1 cup',name:'salsa'},
      {amount:'1 can (10 oz)',name:'Rotel diced tomatoes with green chilies, drained'},
      {amount:'1 package',name:'taco seasoning'},
      {amount:'½',name:'onion, diced'},
      {amount:'for serving',name:'tortillas, cheese, and toppings'},
    ],
    steps: [
      'Place chicken breasts in the slow cooker.',
      'Pour salsa, diced tomatoes, and taco seasoning over the chicken. Add diced onion.',
      'Cook on low for 6–8 hours or high for 3–4 hours.',
      'Shred chicken with two forks right in the pot and stir to combine with the juices.',
      'Serve in tortillas with your favorite toppings.',
    ],
    notes: null,
  },
  {
    title: 'Spicy Sausage and Potato Gnocchi',
    category: 'Pasta', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '25 min',
    ingredients: [
      {amount:'to taste',name:'Cajun/Andouille sausage, sliced'},
      {amount:'1 lb package',name:'potato gnocchi'},
      {amount:'2 jars',name:'diced pimento, drained'},
      {amount:'1 can',name:'diced green chiles'},
      {amount:'1 cup',name:'heavy cream'},
      {amount:'8 oz',name:'pepper jack cheese, shredded'},
      {amount:'to taste',name:'garlic powder, onion powder, salt and pepper'},
    ],
    steps: [
      'Brown sausage slices in a large skillet over medium-high heat. Remove and set aside.',
      'In the same skillet, cook gnocchi per package directions (or pan-fry in a little butter until golden).',
      'Add pimentos and green chiles to the pan. Pour in 1 cup heavy cream and bring to a simmer.',
      'Stir in 8 oz pepper jack cheese until melted and smooth. Season to taste.',
      'Return sausage to the pan. Toss with gnocchi and serve hot.',
    ],
    notes: 'Rich, creamy, and spicy.',
  },
  {
    title: 'Crock Pot Garlic Pork Tenderloin',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '4–6 hours',
    ingredients: [
      {amount:'1–1½ lbs',name:'boneless pork tenderloin'},
      {amount:'2 tsp',name:'all-purpose seasoning'},
      {amount:'¼ cup',name:'low-sodium chicken broth'},
      {amount:'¼ cup',name:'reduced-sodium soy sauce'},
      {amount:'2 tbsp',name:'light brown sugar'},
      {amount:'1 tbsp',name:'minced garlic'},
      {amount:'1 tsp',name:'Dijon mustard'},
      {amount:'for garnish',name:'fresh parsley'},
    ],
    steps: [
      'Season pork tenderloin all over with all-purpose seasoning.',
      'Whisk together chicken broth, soy sauce, brown sugar, garlic, and Dijon mustard. Pour into slow cooker.',
      'Place pork in the slow cooker. Cook on low for 4–6 hours or high for 2–3 hours until internal temp reaches 145°F.',
      'Let rest 5 minutes, then slice and serve drizzled with the cooking juices. Garnish with parsley.',
    ],
    notes: null,
  },
  {
    title: 'Buffalo Chicken Wings — Oven',
    category: 'Appetizers & Snacks', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '1 hour + chill',
    ingredients: [
      {amount:'2 lbs',name:'chicken wings'},
      {amount:'1 tbsp',name:'baking powder'},
      {amount:'1 tsp',name:'kosher salt'},
      {amount:'½ tsp each',name:'black pepper, garlic powder'},
      {amount:'for tossing',name:"Frank's RedHot sauce"},
      {amount:'2 tbsp',name:'butter, melted (to mix with hot sauce)'},
      {amount:'for serving',name:'blue cheese or ranch'},
    ],
    steps: [
      'Pat wings thoroughly dry with paper towels — removing moisture is the most critical step for crispiness.',
      'Toss wings with baking powder, salt, pepper, and garlic powder. Arrange on a wire rack set over a baking sheet.',
      'Refrigerate uncovered for at least 1 hour (or overnight) to further dry the skin.',
      'Bake at 450°F for 45–50 minutes, flipping halfway, until golden and crispy.',
      'Toss immediately with buffalo sauce (Frank\'s + melted butter). Serve with blue cheese or ranch.',
    ],
    notes: 'Baking powder and thorough drying are the keys to crispiness.',
  },
  {
    title: 'Spicy Chicken Sandwiches',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '30 min + marinate',
    ingredients: [
      {amount:'1 cup',name:'buttermilk'},
      {amount:'1',name:'egg'},
      {amount:'½ cup',name:'hot sauce (for marinade)'},
      {amount:'1 pack',name:'boneless skinless chicken thighs (about 8)'},
      {amount:'2 cups',name:'all-purpose flour'},
      {amount:'1 tbsp each',name:'cayenne pepper, garlic powder, paprika'},
      {amount:'1 tsp',name:'salt'},
      {amount:'for frying',name:'vegetable oil'},
      {amount:'for serving',name:'brioche buns, pickles, coleslaw, mayo'},
    ],
    steps: [
      'Whisk buttermilk, egg, and hot sauce. Add chicken thighs, coat well, cover, and chill for at least 1 hour (overnight is better).',
      'Mix flour with cayenne, garlic powder, paprika, and salt in a shallow bowl.',
      'Remove chicken from marinade, letting excess drip off, then dredge in seasoned flour.',
      'Fry in 350°F oil for 5–7 minutes per side until golden and cooked through (165°F internal).',
      'Serve on brioche buns with pickles, coleslaw, and mayo.',
    ],
    notes: 'Inspired by Nashville hot chicken.',
  },
  {
    title: 'Home Fries',
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '45 min',
    ingredients: [
      {amount:'as many as needed',name:'russet potatoes'},
      {amount:'as needed',name:'corn starch'},
      {amount:'to taste',name:'salt and seasoning of choice'},
      {amount:'for frying',name:'vegetable oil'},
      {amount:'to taste',name:'garlic powder, onion powder, paprika (optional)'},
    ],
    steps: [
      'Cut the ends and 2 sides off each potato to square it up, then cut into planks and sticks.',
      'Soak in ice water with salt for 30 minutes. This is the key step — don\'t skip it.',
      'Drain, dry thoroughly with paper towels, then toss with corn starch and seasoning.',
      'Fry in hot vegetable oil (350°F) in batches until golden and crispy. Drain on paper towels. Season immediately.',
    ],
    notes: 'The ice water soak draws out starch and gives you a crispy exterior with a fluffy interior.',
  },
  {
    title: "Bloomin' Onion with Outback Copy-Kat Sauce",
    category: 'Appetizers & Snacks', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '30 min',
    ingredients: [
      {amount:'½ cup',name:'mayonnaise (for dipping sauce)'},
      {amount:'2 tsp',name:'ketchup'},
      {amount:'2 tbsp',name:'horseradish'},
      {amount:'¼ tsp each',name:'paprika, salt, garlic powder, dried oregano'},
      {amount:'pinch',name:'cayenne'},
      {amount:'1 large',name:'sweet onion'},
      {amount:'2 cups',name:'all-purpose flour'},
      {amount:'1 tbsp each',name:'paprika, cayenne, garlic powder, onion powder'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'2',name:'eggs'},
      {amount:'1 cup',name:'milk'},
      {amount:'for frying',name:'vegetable oil'},
    ],
    steps: [
      'Mix all sauce ingredients together. Refrigerate.',
      'Cut the top off the onion, peel, and make 12–16 cuts from top to bottom leaving the root intact to create the bloom.',
      'Mix flour with all dry seasonings. Whisk eggs with milk in a separate bowl.',
      'Dip the onion in the egg wash, then coat thoroughly in the seasoned flour. Repeat for extra crunch.',
      'Deep fry at 375°F, root-side up, for 10 minutes until golden brown. Drain and serve immediately with sauce.',
    ],
    notes: null,
  },
  {
    title: 'Homemade Rolls',
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Makes 15 extra-large or 24 regular rolls', time: '2 hours',
    ingredients: [
      {amount:'5¾ cups',name:'all-purpose flour'},
      {amount:'1 cup',name:'warm water'},
      {amount:'2¼ tsp',name:'instant or active dry yeast'},
      {amount:'2 tbsp',name:'sugar'},
      {amount:'1½ tsp',name:'salt'},
      {amount:'¼ cup',name:'butter, softened'},
      {amount:'2',name:'eggs'},
      {amount:'¾ cup',name:'warm milk'},
      {amount:'for tops',name:'melted butter'},
    ],
    steps: [
      'Combine warm water, sugar, and yeast. Let sit 5 minutes until foamy.',
      'Mix in remaining ingredients (flour, salt, butter, eggs, milk) and knead until smooth, about 8–10 minutes. Dough should be soft but not sticky.',
      'Let rise in a warm place for 1 hour until doubled.',
      'Punch down, divide, and shape into rolls. Place in a greased pan. Let rise another 30 minutes.',
      'Bake at 375°F for 15–20 minutes until golden. Brush hot rolls with butter.',
    ],
    notes: null,
  },
  {
    title: 'Air Fryer Wings',
    category: 'Appetizers & Snacks', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '30 min',
    ingredients: [
      {amount:'3 lbs',name:'chicken wings'},
      {amount:'as needed',name:'olive oil'},
      {amount:'1 tbsp per 2 lbs wings',name:'baking powder'},
      {amount:'to taste',name:'dry rub of choice'},
      {amount:'for finishing',name:'BBQ or wing sauce'},
    ],
    steps: [
      'Pat wings dry with a paper towel.',
      'Toss wings in a light coating of oil.',
      'Add dry rub and baking powder and toss to coat.',
      'Air fry at 400°F for 20–25 minutes, flipping halfway through, until crispy and cooked through.',
      'Toss in sauce and serve immediately.',
    ],
    notes: 'Baking powder is the key to ultra-crispy skin without deep frying.',
  },
  {
    title: 'French Onion White Beans',
    category: 'Soups & Stews', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '1 hour',
    ingredients: [
      {amount:'3 large',name:'yellow onions, sliced'},
      {amount:'3 sprigs',name:'fresh thyme'},
      {amount:'½ cup',name:'sun-dried tomatoes, chopped (save the oil)'},
      {amount:'1 tsp each',name:'sea salt, black pepper, smoked paprika'},
      {amount:'1 head',name:'garlic, roasted or minced'},
      {amount:'½ cup',name:'dry white wine or broth'},
      {amount:'2 cans',name:'white beans (cannellini or Great Northern), drained'},
      {amount:'2 cups',name:'vegetable or chicken broth'},
      {amount:'for serving',name:'Parmesan and crusty bread'},
    ],
    steps: [
      'Heat oil from sun-dried tomatoes in a Dutch oven. Add sliced onions and thyme. Cook over medium-low heat, stirring occasionally, for 30–40 minutes until deep golden brown and caramelized.',
      'Add sun-dried tomatoes, smoked paprika, salt, and pepper. Add garlic. Cook 2 minutes.',
      'Deglaze with white wine or broth, scraping up any browned bits.',
      'Add white beans and broth. Simmer 15–20 minutes until thickened and flavors meld.',
      'Serve with Parmesan and crusty bread for dipping.',
    ],
    notes: 'Caramelized onions, sun-dried tomatoes, and white beans in a rich savory broth.',
  },
  {
    title: 'Mediterranean Chicken and Potatoes',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '1 hour',
    ingredients: [
      {amount:'3 lbs',name:'bone-in, skin-on chicken pieces'},
      {amount:'4',name:'gold potatoes (~2 lbs), cut into thin wedges'},
      {amount:'1 medium',name:'yellow onion, halved and sliced'},
      {amount:'as needed',name:'olive oil'},
      {amount:'1 tsp each',name:'garlic powder, onion powder, paprika, oregano'},
      {amount:'to taste',name:'salt and black pepper'},
      {amount:'juice of 1',name:'lemon'},
      {amount:'for garnish',name:'fresh parsley'},
    ],
    steps: [
      'Preheat oven to 400°F.',
      'Toss chicken and potatoes separately with olive oil, all seasonings, and lemon juice.',
      'Spread onions in a large roasting pan. Arrange chicken skin-side up on top. Tuck potato wedges around the chicken.',
      'Roast for 45–55 minutes until chicken skin is golden and crispy, potatoes are tender, and chicken reaches 165°F internally.',
      'Garnish with fresh parsley and serve with pan juices.',
    ],
    notes: 'One-pan roasted chicken and potatoes with bold Mediterranean flavors.',
  },
  {
    title: 'Mediterranean Shrimp and Zucchini',
    category: 'Seafood', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '20 min',
    ingredients: [
      {amount:'¾–1 lb',name:'large shrimp, peeled and deveined'},
      {amount:'1½ tbsp',name:'dry oregano'},
      {amount:'1 tsp each',name:'ground cumin, ground coriander, sweet paprika'},
      {amount:'2 tbsp',name:'extra-virgin olive oil'},
      {amount:'½ medium',name:'red onion, thinly sliced'},
      {amount:'2 medium',name:'zucchini, sliced'},
      {amount:'3',name:'garlic cloves, minced'},
      {amount:'juice of 1',name:'lemon'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'for garnish',name:'fresh parsley or cilantro'},
    ],
    steps: [
      'Toss shrimp with oregano, cumin, coriander, paprika, salt, and pepper.',
      'Heat olive oil in a large skillet over medium-high. Add onion and cook 3 minutes until softened.',
      'Add zucchini and cook 3–4 minutes until just tender. Add garlic and cook 30 seconds.',
      'Add shrimp and cook 2–3 minutes per side until pink and cooked through.',
      'Squeeze lemon over everything. Garnish with parsley and serve hot.',
    ],
    notes: 'Light, fresh, and packed with Mediterranean-spiced shrimp.',
  },
  {
    title: "Smoked Mac 'n Cheese",
    category: 'Sides', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 20+ (scale down as needed)', time: '2–3 hours',
    ingredients: [
      {amount:'2 large blocks',name:'Velveeta cheese, cubed'},
      {amount:'2 lbs',name:'elbow macaroni, cooked and drained'},
      {amount:'1 stick',name:'butter'},
      {amount:'1 pint',name:'heavy whipping cream'},
      {amount:'½ gallon',name:'whole milk'},
      {amount:'to taste',name:'BBQ rub (Meat Church Honey Hog recommended)'},
      {amount:'optional',name:'shredded cheddar for top layer'},
    ],
    steps: [
      'Cook macaroni per package directions. Drain.',
      'Melt 1 stick butter in a large pot. Add ½ gallon milk and 1 pint cream, bringing to a gentle simmer.',
      'Stir in cubed Velveeta until fully melted and smooth.',
      'Stir in cooked pasta. Season with BBQ rub to taste. Pour into a large aluminum pan.',
      'Smoke at 225–250°F for 1½–2 hours stirring occasionally. Top with more rub or shredded cheddar in the last 30 minutes.',
    ],
    notes: 'A showstopper BBQ side. Scale this down for a normal-sized family.',
  },
  {
    title: 'Fried Chicken',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–6', time: '4+ hours',
    ingredients: [
      {amount:'1 whole chicken cut up',name:'or 8 pieces preferred cuts'},
      {amount:'2 tsp each',name:'kosher salt, garlic powder, onion powder'},
      {amount:'2 cups',name:'buttermilk'},
      {amount:'2 tbsp',name:'hot sauce'},
      {amount:'2 cups',name:'all-purpose flour'},
      {amount:'1 tsp each',name:'paprika, cayenne, salt, pepper'},
      {amount:'for frying',name:'vegetable oil'},
    ],
    steps: [
      'Season chicken with salt, garlic powder, and onion powder. Soak in buttermilk mixed with hot sauce for at least 4 hours (overnight preferred).',
      'Mix flour with paprika, cayenne, salt, and pepper in a shallow bowl.',
      'Remove chicken from buttermilk, letting excess drip off. Dredge in seasoned flour, pressing to coat. Let sit on a rack for 15 minutes.',
      'Heat 2–3 inches of vegetable oil to 325–350°F in a deep skillet or Dutch oven. Fry chicken in batches: dark pieces 12–14 minutes, white pieces 10–12 minutes, turning once, until golden and 165°F internal.',
      'Drain on a wire rack (not paper towels — keeps it crispier). Season with salt immediately.',
    ],
    notes: 'A proper buttermilk-brined Southern fried chicken. Worth every step.',
  },
  {
    title: 'Buffalo Chicken Sandwich (Crispy)',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '30 min + marinate',
    ingredients: [
      {amount:'4',name:'boneless skinless chicken thighs or breasts'},
      {amount:'1 cup',name:'buttermilk'},
      {amount:'½ cup',name:'hot sauce (for marinade)'},
      {amount:'1½ cups',name:'all-purpose flour'},
      {amount:'1 tbsp',name:'cornstarch'},
      {amount:'1 tsp each',name:'paprika, garlic powder, onion powder, cayenne'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'for frying',name:'vegetable oil'},
      {amount:'for tossing',name:'Frank\'s Buffalo sauce'},
      {amount:'for serving',name:'brioche buns, pickles, coleslaw, mayo'},
    ],
    steps: [
      'Marinate chicken in buttermilk and hot sauce for at least 1 hour.',
      'Mix flour, cornstarch, and all dry seasonings in a shallow bowl.',
      'Remove chicken, let excess drip off. Dredge in flour, back in the buttermilk, then dredge in flour again for extra crunch.',
      'Fry in 350°F oil for 5–7 minutes per side until golden brown and 165°F internal. Drain on a rack.',
      'Toss immediately in Buffalo sauce. Serve on toasted brioche with pickles, coleslaw, and mayo.',
    ],
    notes: 'Double-dredge is the key to extra crunch.',
  },
  {
    title: 'Pork Tenderloin with Honey Garlic Sauce',
    category: 'Beef & Pork', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4–5', time: '35 min',
    ingredients: [
      {amount:'2',name:'pork tenderloins (~1 lb each), silverskin removed'},
      {amount:'½ tsp each',name:'garlic powder, paprika, cumin, onion powder'},
      {amount:'to taste',name:'salt and black pepper'},
      {amount:'1½ tbsp',name:'olive oil'},
      {amount:'3',name:'garlic cloves, very finely chopped'},
      {amount:'1½ tbsp',name:'butter'},
      {amount:'¼ cup',name:'honey'},
      {amount:'3 tbsp',name:'low-sodium soy sauce'},
      {amount:'2 tbsp',name:'cider vinegar or rice vinegar'},
    ],
    steps: [
      'Preheat oven to 400°F. Mix all spices and coat tenderloins evenly.',
      'Heat 1½ tbsp olive oil in an oven-safe skillet over medium-high. Sear tenderloin all over, 2 minutes per side.',
      'Mix sauce: 3 minced garlic cloves, 1½ tbsp butter, ¼ cup honey, 3 tbsp soy sauce, 2 tbsp vinegar. Pour over the pork in the skillet.',
      'Roast in oven 12–15 minutes until internal temp reaches 145°F.',
      'Rest 5 minutes before slicing. Spoon pan sauce over top. Serve with mashed potatoes or roasted vegetables.',
    ],
    notes: null,
  },
  {
    title: 'Roasted Lemon Chicken & Potato Wedges',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 4', time: '50 min',
    ingredients: [
      {amount:'2',name:'lemons'},
      {amount:'1¼ lbs',name:'bone-in, skin-on chicken thighs (2–3 pieces)'},
      {amount:'1¼ lbs',name:'Yukon Gold potatoes, halved and cut into ½-inch wedges'},
      {amount:'1¾ tsp',name:'kosher salt, divided'},
      {amount:'½ tsp',name:'black pepper'},
      {amount:'3 tbsp',name:'olive oil'},
      {amount:'4',name:'garlic cloves, smashed'},
      {amount:'to taste',name:'fresh thyme or rosemary sprigs'},
    ],
    steps: [
      'Preheat oven to 425°F.',
      'Zest and juice one lemon. Cut the second lemon into wedges.',
      'Toss potato wedges with 2 tbsp olive oil, ¾ tsp salt, and pepper. Spread on a large rimmed baking sheet.',
      'Rub chicken with remaining olive oil, lemon zest, lemon juice, garlic, remaining salt, and herbs. Nestle among the potatoes.',
      'Roast 35–45 minutes until chicken skin is golden and crispy and potatoes are tender. Squeeze roasted lemon wedges over everything before serving.',
    ],
    notes: 'A simple, classic roasted dinner brightened with lemon and herbs.',
  },
  {
    title: 'Pan-Seared Turkey Breast',
    category: 'Chicken', submitted_by: 'Family Collection', initials: 'DAM',
    serves: 'Serves 2', time: '15 min',
    ingredients: [
      {amount:'8–10 oz',name:'turkey breast, cut into 4 thin slices'},
      {amount:'to taste',name:'sea salt and freshly ground pepper'},
      {amount:'1 tbsp',name:'neutral oil'},
      {amount:'1 tbsp',name:'chopped mixed fresh herbs (thyme, sage, rosemary)'},
      {amount:'2 tbsp',name:'butter'},
      {amount:'for serving',name:'lemon wedge'},
    ],
    steps: [
      'Pat turkey slices dry. Season with salt and pepper on both sides.',
      'Heat oil in a skillet over medium-high until shimmering.',
      'Add turkey slices and cook 2–3 minutes per side until golden and cooked through (165°F internal).',
      'Reduce heat to medium. Add butter and herbs. Baste turkey with the melted herb butter for 30 seconds.',
      'Serve immediately with a squeeze of lemon.',
    ],
    notes: 'A quick, elegant weeknight dinner.',
  },
]

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  if (req.headers['x-seed-secret'] !== process.env.SEED_SECRET) return res.status(401).json({ error: 'Unauthorized' })

  try {
    const batchSize = 10
    let inserted = 0
    for (let i = 0; i < recipes.length; i += batchSize) {
      const batch = recipes.slice(i, i + batchSize)
      const { data, error } = await supabase.from('recipes').insert(batch).select()
      if (error) throw error
      inserted += data.length
    }
    return res.status(200).json({ success: true, inserted })
  } catch (err) {
    return res.status(500).json({ error: err.message })
  }
}
