import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.VITE_SUPABASE_URL,
  process.env.VITE_SUPABASE_ANON_KEY
)

// All 50 core recipes
const recipes = [
  {
    title: 'Zesty Sheet Pan Caprese Chicken',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 6', time: '1 hr 45 min',
    ingredients: [
      {amount:'3',name:'boneless, skinless chicken breasts, butterflied or 6 cutlets'},
      {amount:'~1 cup',name:'store-bought Italian dressing'},
      {amount:'1 lb',name:'baby creamer potatoes, halved or quartered'},
      {amount:'1 packet (0.6 oz)',name:'zesty Italian dressing seasoning'},
      {amount:'12 oz',name:'green beans, trimmed'},
      {amount:'1',name:'lemon, juiced'},
      {amount:'½ cup',name:'basil pesto'},
      {amount:'2 small',name:'vine-ripened tomatoes, thinly sliced'},
      {amount:'6–8 slices',name:'deli-style mozzarella cheese'},
      {amount:'6 slices',name:'prosciutto, torn into small pieces'},
      {amount:'to taste',name:'olive oil, kosher salt'},
      {amount:'for drizzling',name:'balsamic glaze'},
    ],
    steps: [
      'In a large resealable bag, combine the chicken and Italian dressing. Seal and refrigerate to marinate for 1 to 4 hours.',
      'Preheat oven to 400°F. Line a baking sheet with foil and grease with cooking spray.',
      'Toss potatoes with a splash of olive oil, half the Italian seasoning packet, and a pinch of salt. Spread on the baking sheet. Bake 20 minutes to par-cook.',
      'In the same bowl, toss green beans with olive oil, remaining seasoning packet, a pinch of salt, and lemon juice.',
      'Remove potatoes from oven and push to one side. Arrange chicken on the other side. Layer each cutlet with pesto, tomato, mozzarella, and prosciutto. Add green beans to the center.',
      'Bake another 20–25 minutes until chicken reaches 165°F and potatoes are fork-tender. Drizzle with balsamic glaze and serve.',
    ],
    notes: 'Everything fits on one pan. For more browning, use two pans.',
  },
  {
    title: 'Air Fryer Taquitos',
    category: 'Appetizers & Snacks', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '30 min',
    ingredients: [
      {amount:'2½–3 cups',name:'shredded rotisserie chicken'},
      {amount:'¾ cup',name:'salsa of choice'},
      {amount:'½ cup',name:'shredded Mexican blend cheese'},
      {amount:'4 oz',name:'cream cheese, softened'},
      {amount:'1 package',name:'taco seasoning'},
      {amount:'10–12',name:'6-inch soft white corn tortillas'},
      {amount:'as needed',name:'nonstick cooking spray'},
    ],
    steps: [
      'Preheat the air fryer to 400°F.',
      'In a large bowl, combine chicken, salsa, shredded cheese, cream cheese, and taco seasoning. Stir until well combined.',
      'Wrap tortillas in a damp tea towel and microwave on high for 60 seconds to warm them.',
      'Scoop a heaping spoonful of filling onto a tortilla and spread across the middle. Roll up into a cigar. Repeat with all filling and tortillas.',
      'Spray the air fryer basket with cooking spray. Arrange taquitos in a single layer and spray tops with cooking spray.',
      'Cook 10–12 minutes until golden brown and crispy. Store extras in the freezer up to 3 months; reheat at 400°F for 6–8 minutes.',
    ],
    notes: 'Great freezer meal. Can substitute pulled pork or any leftover cooked meat.',
  },
  {
    title: 'Biscuit Beef Pie',
    category: 'Beef & Pork', submitted_by: 'Family Collection',
    serves: 'Serves 6–8', time: '45 min',
    ingredients: [
      {amount:'2 lbs',name:'lean ground beef (95/5)'},
      {amount:'1 tsp each',name:'black pepper, garlic powder, onion powder'},
      {amount:'½ tsp',name:'kosher salt'},
      {amount:'2 cans (14.5 oz)',name:'mixed vegetables, drained'},
      {amount:'1 can (10.5 oz)',name:'cream of mushroom soup'},
      {amount:'1 can (10.5 oz)',name:'golden mushroom soup'},
      {amount:'½ cup',name:'whole milk'},
      {amount:'1 package (11.36 oz)',name:'Red Lobster Cheddar Bay Biscuit Mix'},
      {amount:'½ cup',name:'shredded sharp cheddar cheese'},
      {amount:'2 tbsp',name:'butter, melted'},
    ],
    steps: [
      'Preheat oven to 425°F.',
      'In a wide oven-safe skillet over medium-high, cook 2 lbs ground beef with 1 tsp each pepper, garlic powder, onion powder, and ½ tsp salt until browned, 6–8 minutes. Drain fat.',
      'Stir in both cans of soup, both cans of vegetables, and ½ cup milk. Spread into an even layer.',
      'Prepare biscuit mix per package instructions, adding ½ cup shredded cheddar to the dough. Scoop in 2–3 tbsp portions over the filling.',
      'Bake uncovered 15 minutes until biscuits are golden. Brush tops with 2 tbsp melted butter and sprinkle with the included garlic-herb packet. Let stand 10 minutes before serving.',
    ],
    notes: 'Southern spin on shepherd\'s pie. The cheddar biscuit mix can be swapped with premade biscuit rounds.',
  },
  {
    title: 'Slow Cooker Chicken & Gravy',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 4–6', time: '5–8 hours',
    ingredients: [
      {amount:'1½–2 lbs',name:'boneless, skinless chicken breasts or thighs'},
      {amount:'2 cans (10.5 oz)',name:'golden mushroom soup'},
      {amount:'2 packets (.87 oz)',name:'brown gravy mix'},
      {amount:'1 packet (1 oz)',name:'onion soup mix'},
      {amount:'2 cups',name:'water'},
      {amount:'1 bag (10–12 oz)',name:'frozen mixed vegetables (California blend)'},
      {amount:'½ cup',name:'heavy cream'},
      {amount:'for serving',name:'mashed potatoes or cooked rice'},
    ],
    steps: [
      'Trim any fat off the chicken and arrange in an even layer in the slow cooker.',
      'Whisk together both cans mushroom soup, both gravy mix packets, the onion soup mix, and 2 cups water. Pour over chicken. Add frozen vegetables on top.',
      'Cook on low 6–8 hours or high 4–5 hours until chicken is tender and reaches 165°F.',
      'Shred chicken with forks right in the slow cooker. Stir in ½ cup heavy cream. Cook on low another 15–30 minutes until warmed through.',
      'Serve over mashed potatoes.',
    ],
    notes: 'You can\'t screw up this recipe.',
  },
  {
    title: 'One-Pot French Onion Pasta',
    category: 'Pasta', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '45 min',
    ingredients: [
      {amount:'3 tbsp',name:'butter'},
      {amount:'2 medium',name:'white or yellow onions, thinly sliced'},
      {amount:'3 cups',name:'beef stock'},
      {amount:'2 packets (1 oz each)',name:'onion soup mix'},
      {amount:'1 tbsp',name:'soy sauce or Worcestershire sauce'},
      {amount:'½ tsp',name:'black pepper'},
      {amount:'1 tbsp',name:'minced garlic (3 cloves)'},
      {amount:'8 oz',name:'rigatoni or other medium pasta shape'},
      {amount:'½ cup',name:'heavy cream'},
      {amount:'8 slices',name:'Swiss cheese, or 2 cups shredded Gruyère'},
    ],
    steps: [
      'In a Dutch oven over medium heat, melt 3 tbsp butter. Add onions, cover, and cook stirring occasionally 15–20 minutes until golden brown.',
      'Whisk together 3 cups beef stock, both onion soup mix packets, 1 tbsp soy sauce, and ½ tsp pepper.',
      'Stir garlic into onions and cook 1 minute. Pour in stock mixture and bring to a boil.',
      'Stir in pasta. Reduce to a gentle simmer, cover, and cook 12–15 minutes until pasta is tender.',
      'Stir in ½ cup heavy cream, then arrange Swiss cheese on top. Cover 3 minutes to melt. Serve right away.',
    ],
    notes: 'Add crusty bread or garlic bread for dunking.',
  },
  {
    title: 'Cajun Cream Steak & Potatoes',
    category: 'Beef & Pork', submitted_by: 'Family Collection',
    serves: 'Serves 3–4', time: '30 min',
    ingredients: [
      {amount:'1–1½ lbs',name:'baby gold potatoes, cut bite-size'},
      {amount:'to taste',name:'Cajun or Creole seasoning, kosher salt'},
      {amount:'1–1½ lbs',name:'cubed stew meat or sirloin steak'},
      {amount:'to taste',name:'black pepper'},
      {amount:'¼ cup',name:'water'},
      {amount:'2 cups',name:'heavy cream'},
      {amount:'½ tsp',name:'garlic powder'},
      {amount:'1 cup',name:'freshly grated Parmesan, plus more for garnish'},
      {amount:'for garnish',name:'chopped fresh parsley'},
    ],
    steps: [
      'Preheat air fryer to 400°F. Toss potatoes with olive oil and Cajun seasoning. Air-fry until crispy and tender, about 15 minutes.',
      'Toss steak with olive oil, salt, and pepper. Sear in a hot wide skillet over medium-high, 2–3 minutes per side. Transfer to a plate.',
      'Reduce heat to low. Add ¼ cup water and scrape up browned bits. Once evaporated, pour in 2 cups heavy cream, ½ tsp garlic powder, and 1 tsp Cajun seasoning. Simmer until cream comes to a gentle simmer.',
      'Stir in 1 cup Parmesan until melted and smooth.',
      'Add steak and potatoes to the sauce. Simmer a couple minutes until heated through. Serve hot garnished with more Parmesan and parsley.',
    ],
    notes: 'Serve with garlic bread to mop up the sauce.',
  },
  {
    title: 'One-Pot Queso Chicken & Rice',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '35 min',
    ingredients: [
      {amount:'1½–2 lbs',name:'boneless, skinless chicken breasts or thighs, cut bite-size'},
      {amount:'½ tsp each',name:'kosher salt, black pepper, ground cumin, smoked paprika'},
      {amount:'as needed',name:'olive or vegetable oil, 1 tbsp butter'},
      {amount:'2 boxes (6.8 oz)',name:'Rice-A-Roni Spanish Rice with seasoning packets'},
      {amount:'2 cans (10 oz)',name:'Rotel diced tomatoes with green chilies'},
      {amount:'1 can (15 oz)',name:'whole kernel corn, drained'},
      {amount:'1 can (15 oz)',name:'black beans, drained and rinsed (optional)'},
      {amount:'8 oz (~2 cups)',name:'Velveeta queso blanco, cubed'},
      {amount:'1 can (5 oz)',name:'evaporated milk'},
      {amount:'1½ cups',name:'water'},
    ],
    steps: [
      'Toss chicken with ½ tsp each salt, pepper, cumin, and paprika.',
      'Heat oil in a wide skillet with lid over medium-high. Cook chicken flipping once until browned and cooked through, 5–8 minutes. Transfer to a plate.',
      'Reduce heat to medium. Add 1 tbsp butter and the Rice-A-Roni (reserving seasoning packets), toasting a couple minutes. Stir in tomatoes with their juices, corn, beans if using, and 1½ cups water. Add seasoning packets. Bring to a simmer, cover, cook 10 minutes.',
      'Fold in chicken. Scatter Velveeta cubes on top and pour evaporated milk over everything. Cover and cook another 5–10 minutes until rice is tender and chicken reaches 165°F.',
      'Stir the melted cheese into the rice until smooth. Serve hot.',
    ],
    notes: 'If too much queso sounds impossible, double up the Velveeta.',
  },
  {
    title: 'One-Pan Italian Sausage Pasta',
    category: 'Pasta', submitted_by: 'Family Collection',
    serves: 'Serves 4–6', time: '30 min',
    ingredients: [
      {amount:'1 lb',name:'mild ground Italian sausage'},
      {amount:'½ cup',name:'oil-packed sun-dried tomatoes, drained and chopped'},
      {amount:'1 tbsp',name:'minced garlic (3 cloves)'},
      {amount:'¼ tsp each',name:'crushed red pepper flakes, onion powder'},
      {amount:'8 oz',name:'short pasta (penne, rigatoni, or fusilli)'},
      {amount:'2 cups',name:'chicken stock'},
      {amount:'1 cup',name:'heavy cream'},
      {amount:'1 cup',name:'grated Parmesan, plus more for garnish'},
      {amount:'1 tsp',name:'Italian seasoning'},
      {amount:'a couple handfuls',name:'fresh baby spinach'},
    ],
    steps: [
      'Brown sausage in a wide skillet over medium-high, breaking into crumbles, 10–15 minutes. Transfer to a plate.',
      'In the same skillet, stir in sun-dried tomatoes, garlic, onion powder, and red pepper flakes. Cook 1 minute. Stir in pasta to combine.',
      'Pour in 2 cups chicken stock and 1 cup heavy cream. Bring to a simmer, reduce to low, cover, and cook 15–20 minutes until pasta is tender.',
      'Remove from heat, stir in 1 cup Parmesan. Scatter spinach on top, cover a few minutes to wilt, then stir in.',
      'Serve hot garnished with more Parmesan.',
    ],
    notes: 'Use oil-packed sun-dried tomatoes, not dry.',
  },
  {
    title: 'Red Pepper Pasta',
    category: 'Pasta', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '20 min',
    ingredients: [
      {amount:'8 oz',name:'cavatappi pasta'},
      {amount:'2 tbsp',name:'butter'},
      {amount:'1',name:'red bell pepper, finely diced'},
      {amount:'½ large',name:'red onion, finely diced'},
      {amount:'½ cup',name:'oil-packed sun-dried tomatoes, drained and chopped'},
      {amount:'1 tbsp',name:'minced garlic (3 cloves)'},
      {amount:'3 tbsp',name:'tomato paste'},
      {amount:'1 tsp each',name:'Italian seasoning, black pepper'},
      {amount:'½ tsp each',name:'garlic powder, smoked paprika'},
      {amount:'¼ tsp',name:'crushed red pepper flakes (or more)'},
      {amount:'½ cup',name:'heavy cream'},
      {amount:'1 cup',name:'freshly grated Asiago cheese, plus more for garnish'},
    ],
    steps: [
      'Bring a large pot of generously salted water to a boil. Cook pasta until al dente. Reserve 1 cup pasta water, then drain.',
      'In a deep wide skillet over medium heat, melt 2 tbsp butter. Add bell pepper and onion and cook about 10 minutes until tender.',
      'Reduce heat to medium-low. Add sun-dried tomatoes and garlic, fry 2 minutes. Add 3 tbsp tomato paste and cook 5 minutes until caramelized. Stir in all seasonings.',
      'Stir in reserved pasta water and ½ cup heavy cream. Bring to a simmer.',
      'Remove from heat, add cooked pasta and toss to coat. Stir in 1 cup Asiago. Serve immediately garnished with more cheese.',
    ],
    notes: 'Parmesan works great if you don\'t have Asiago.',
  },
  {
    title: 'Chicken Fried Steak with Gravy',
    category: 'Beef & Pork', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '45 min',
    ingredients: [
      {amount:'4',name:'cubed steaks (minute steak), about ¼ lb each'},
      {amount:'½ tsp each',name:'kosher salt, black pepper for seasoning steaks'},
      {amount:'¾ cup',name:'all-purpose flour, divided'},
      {amount:'2 tbsp',name:'cornstarch'},
      {amount:'½ tsp each',name:'garlic powder, onion powder, smoked paprika'},
      {amount:'2 cups',name:'whole milk, plus more as needed'},
      {amount:'1',name:'large egg'},
      {amount:'for frying',name:'vegetable oil'},
    ],
    steps: [
      'Pat steaks dry. Pound to even thickness if needed. Season all over with ½ tsp each salt and pepper.',
      'Combine ½ cup flour with 2 tbsp cornstarch, ½ tsp each salt, pepper, garlic powder, onion powder, and paprika. Whisk ½ cup milk with the egg in a second bowl.',
      'Dredge each steak in seasoned flour, dip in milk mixture, dredge in flour again. Rest on a wire rack.',
      'Pour ½ inch vegetable oil into a deep skillet over medium-high. Fry steaks 5 minutes on first side, 4 minutes on second until golden and 165°F internal. Drain on a rack.',
      'Pour off all but ¼ cup oil. Whisk in remaining ¼ cup flour for 90 seconds. Slowly whisk in remaining 1½ cups milk until smooth. Season with 1 tsp pepper and ½ tsp salt. Serve steaks with mashed potatoes and gravy.',
    ],
    notes: null,
  },
  {
    title: 'Pepper Steak',
    category: 'Beef & Pork', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '40 min',
    ingredients: [
      {amount:'1½ lbs',name:'sirloin steak or any cut you prefer'},
      {amount:'as needed',name:'olive oil, kosher salt, black pepper'},
      {amount:'1',name:'bell pepper (any color), sliced into thin strips'},
      {amount:'1 medium',name:'white or yellow onion, sliced into thin strips'},
      {amount:'2 tbsp',name:'all-purpose flour'},
      {amount:'2 cups',name:'beef stock'},
      {amount:'1 can (8 oz)',name:'tomato sauce'},
      {amount:'1 tsp',name:'garlic powder'},
      {amount:'½ tsp',name:'crushed red pepper flakes'},
      {amount:'for serving',name:'fresh-cooked rice'},
    ],
    steps: [
      'Place steak in the freezer for 20–30 minutes to firm up for easier slicing.',
      'Slice steak into very thin (⅛ inch) strips cutting against the grain. Toss with olive oil, salt, and pepper.',
      'Sear steak in a hot wide skillet over medium-high, about 90 seconds per side. Transfer to a plate.',
      'Add bell pepper and onion to the pan. Cook over medium-low about 5 minutes until softened. Sprinkle over 2 tbsp flour and stir 2 minutes. Pour in 2 cups beef stock, stirring to make a smooth sauce.',
      'Add 1 can tomato sauce, ½ tsp black pepper, 1 tsp garlic powder, and ½ tsp red pepper flakes. Bring to a gentle simmer, return steak to the pan, and simmer 5 minutes. Serve hot over rice.',
    ],
    notes: 'A family recipe with tomato sauce. Have all ingredients ready before you start.',
  },
  {
    title: 'Sticky-Sweet Air Fryer Salmon Bites',
    category: 'Seafood', submitted_by: 'Family Collection',
    serves: 'Serves 3–4', time: '20 min',
    ingredients: [
      {amount:'⅓ cup',name:'soy sauce'},
      {amount:'¼ cup',name:'packed brown sugar'},
      {amount:'2 tbsp',name:'honey'},
      {amount:'2 tsp each',name:'unseasoned rice vinegar, toasted sesame oil'},
      {amount:'1 tsp each',name:'ground ginger, onion powder, garlic powder'},
      {amount:'½ tsp',name:'crushed red pepper flakes'},
      {amount:'1 lb',name:'salmon fillets, cut into 1-inch pieces'},
      {amount:'1 tbsp',name:'cornstarch'},
      {amount:'for garnish',name:'toasted sesame seeds, sliced green onions'},
      {amount:'for serving',name:'rice, noodles, or salad'},
    ],
    steps: [
      'Preheat air fryer to 400°F. Whisk together all sauce ingredients.',
      'Toss salmon pieces in about a quarter of the marinade. Arrange in a single layer in a sprayed air fryer basket.',
      'Cook 9 minutes until just firm (12 minutes for more caramelized). Work in batches if needed.',
      'Whisk cornstarch with 1 tbsp cold water. Pour remaining marinade into a small saucepan, bring to a simmer, whisk in the cornstarch slurry, and cook until thickened, about 2 minutes.',
      'Toss cooked salmon gently in the sauce. Top with sesame seeds and green onions. Serve over rice, noodles, or salad.',
    ],
    notes: 'Use the basket not the flat sheet — the sheet causes burning. Works great with cubed chicken too.',
  },
  {
    title: 'Air Fryer Chicken Parmesan with Angel Hair Alfredo',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 2', time: '30 min',
    ingredients: [
      {amount:'2',name:'boneless, skinless chicken cutlets (4–6 oz each)'},
      {amount:'to taste',name:'kosher salt and black pepper'},
      {amount:'½ cup each',name:'finely grated Parmesan cheese, panko bread crumbs'},
      {amount:'1 tsp',name:'Italian seasoning'},
      {amount:'½ tsp',name:'garlic powder'},
      {amount:'¼ tsp',name:'crushed red pepper flakes'},
      {amount:'1',name:'large egg'},
      {amount:'½ cup',name:'all-purpose flour'},
      {amount:'as needed',name:'nonstick cooking spray'},
      {amount:'¼ cup',name:'pizza or marinara sauce'},
      {amount:'4 slices',name:'mozzarella cheese'},
    ],
    steps: [
      'Preheat air fryer to 375°F. Let chicken rest at room temp 15 minutes. If uneven, pound to even thickness. Season with salt and pepper.',
      'Mix Parmesan, panko, Italian seasoning, ½ tsp salt, ½ tsp pepper, garlic powder, and red pepper flakes on a wide plate. Whisk egg in a bowl. Spread flour on another plate.',
      'Dredge chicken in flour, dip in egg, then press into the Parmesan-panko mixture to coat completely.',
      'Spray basket with cooking spray. Air fry 10–12 minutes flipping halfway until chicken reaches 165°F and is golden all over.',
      'Flip once more, spread pizza sauce on each cutlet, top with 2 mozzarella slices each. Air fry another 3–5 minutes until cheese is melted and browning. Serve garnished with parsley.',
    ],
    notes: 'CJ\'s most favorite dinner.',
  },
  {
    title: 'Spicy Chicken Meatballs in Coconut Curry Sauce',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '30 min',
    ingredients: [
      {amount:'1 lb',name:'ground chicken'},
      {amount:'1 cup',name:'unseasoned fine bread crumbs'},
      {amount:'1',name:'large egg, lightly beaten'},
      {amount:'2 tbsp each',name:'low-sodium soy sauce, red curry paste'},
      {amount:'1',name:'green onion, chopped'},
      {amount:'½ tsp each',name:'onion powder, garlic powder, ground ginger, crushed red pepper flakes, ground cumin'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'½ medium',name:'white onion, thinly sliced'},
      {amount:'1',name:'red bell pepper, thinly sliced'},
      {amount:'1 tbsp',name:'red curry paste'},
      {amount:'1 can (14 oz)',name:'full-fat unsweetened coconut milk'},
      {amount:'1 tbsp',name:'low-sodium soy sauce'},
      {amount:'¼ tsp each',name:'crushed red pepper flakes, ground ginger'},
      {amount:'for serving',name:'fresh-cooked rice, chopped cilantro'},
    ],
    steps: [
      'Combine ground chicken, bread crumbs, egg, 2 tbsp soy sauce, 2 tbsp red curry paste, green onion, and all meatball spices. Mix and form into 1½-inch meatballs.',
      'Heat 2 tbsp olive oil in a large skillet over medium-high. Brown meatballs on all sides, about 6–8 minutes. Remove and set aside.',
      'In the same pan, sauté sliced onion and red bell pepper until softened, about 4 minutes.',
      'Add 1 tbsp red curry paste, the coconut milk, 1 tbsp soy sauce, and remaining sauce spices. Stir and bring to a simmer.',
      'Return meatballs to the pan. Simmer 5–7 minutes until cooked through. Serve over rice garnished with cilantro.',
    ],
    notes: 'For extra saucy, add a second can of coconut milk and double the curry sauce seasonings.',
  },
  {
    title: 'Marry Me Chicken',
    category: 'Chicken', submitted_by: "Chrissy's Favorite",
    serves: 'Serves 4', time: '30 min',
    ingredients: [
      {amount:'3 large',name:'chicken breasts, sliced lengthwise into thin cutlets'},
      {amount:'½ tsp',name:'salt'},
      {amount:'¼ tsp',name:'black pepper'},
      {amount:'6 tbsp',name:'all-purpose flour'},
      {amount:'2 tbsp each',name:'olive oil, butter'},
      {amount:'3',name:'garlic cloves, minced'},
      {amount:'1 cup',name:'chicken broth'},
      {amount:'1 cup',name:'heavy cream'},
      {amount:'½ cup',name:'sun-dried tomatoes, chopped'},
      {amount:'1 tsp each',name:'dried thyme, dried oregano'},
      {amount:'½ cup',name:'freshly grated Parmesan'},
      {amount:'for garnish',name:'fresh basil'},
    ],
    steps: [
      'Season chicken with ½ tsp salt and ¼ tsp pepper. Dredge in 6 tbsp flour.',
      'Heat 2 tbsp olive oil and 2 tbsp butter in a large oven-safe skillet over medium-high. Sear chicken 3–4 minutes per side until golden. Remove to a plate.',
      'Add 3 minced garlic cloves to the pan, cook 30 seconds. Add 1 cup chicken broth and scrape up browned bits. Stir in 1 cup cream, ½ cup sun-dried tomatoes, 1 tsp thyme, and 1 tsp oregano.',
      'Simmer 3–5 minutes until slightly thickened. Stir in ½ cup Parmesan.',
      'Return chicken to the pan, spoon sauce over. Bake at 375°F for 15 minutes until cooked through. Garnish with fresh basil.',
    ],
    notes: 'So good it might get someone to propose. Serve over pasta or with crusty bread.',
  },
  {
    title: 'White Chicken Chili',
    category: 'Soups & Stews', submitted_by: 'Family Collection',
    serves: 'Serves 8–10', time: '30 min',
    ingredients: [
      {amount:'48 oz jar',name:'Great Northern beans, precooked'},
      {amount:'1 jar',name:'green salsa'},
      {amount:'16 oz',name:'shredded jack or pepper jack cheese'},
      {amount:'2 cups',name:'milk (whole or half-and-half)'},
      {amount:'2 large cans',name:'shredded chicken, or 3–4 cups cooked shredded chicken'},
      {amount:'1 can',name:'cream of chicken soup'},
      {amount:'1 can',name:'chicken broth'},
      {amount:'1 packet',name:'taco seasoning'},
      {amount:'1 tsp',name:'cumin'},
      {amount:'for serving',name:'green onions, sour cream, jalapeños'},
    ],
    steps: [
      'Combine beans, green salsa, chicken broth, and cream of chicken soup in a large pot over medium heat.',
      'Stir in taco seasoning and cumin. Bring to a simmer.',
      'Add shredded chicken and 2 cups milk. Stir to combine.',
      'Add shredded cheese a handful at a time, stirring until fully melted.',
      'Simmer 15–20 minutes. Serve topped with green onions, sour cream, and jalapeños.',
    ],
    notes: 'One of the most-shared recipes in the collection. Great with cornbread.',
  },
  {
    title: 'Zuppa Toscana',
    category: 'Soups & Stews', submitted_by: 'Family Collection',
    serves: 'Serves 6–8', time: '45 min',
    ingredients: [
      {amount:'1½ lbs',name:'Italian sausage (mild or hot)'},
      {amount:'1 large',name:'onion, chopped'},
      {amount:'4 cloves',name:'garlic, minced'},
      {amount:'¼–½ tsp',name:'crushed red pepper'},
      {amount:'2 tsp',name:'kosher salt'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'6 cups',name:'chicken broth'},
      {amount:'3 large',name:'russet potatoes, thinly sliced or cubed'},
      {amount:'1 bunch',name:'kale, stems removed, leaves torn'},
      {amount:'1 cup',name:'heavy cream'},
      {amount:'for serving',name:'grated Parmesan'},
    ],
    steps: [
      'Brown Italian sausage in a large pot, breaking into crumbles. Drain excess fat. Remove and set aside.',
      'Heat 2 tbsp olive oil in the same pot. Sauté onion, garlic, and red pepper until onion is softened, about 5 minutes.',
      'Add 6 cups chicken broth and potatoes. Bring to a boil. Simmer until potatoes are tender, about 15 minutes.',
      'Return sausage to the pot. Stir in kale and cook until wilted, 3–5 minutes.',
      'Stir in 1 cup heavy cream and heat through. Season with salt. Serve with grated Parmesan.',
    ],
    notes: 'Homemade Olive Garden classic.',
  },
  {
    title: 'Potato Soup',
    category: 'Soups & Stews', submitted_by: 'Family Collection',
    serves: 'Serves 6–8', time: '45 min',
    ingredients: [
      {amount:'½ lb',name:'bacon, diced'},
      {amount:'6–8 tbsp',name:'reserved bacon grease or butter'},
      {amount:'½ large',name:'white onion, diced'},
      {amount:'2–3 tsp',name:'minced garlic'},
      {amount:'¼–½ cup',name:'all-purpose flour'},
      {amount:'4–5 large',name:'russet potatoes, peeled and cubed'},
      {amount:'3–4 cups',name:'chicken or vegetable broth'},
      {amount:'1½ cups',name:'whole milk or heavy cream'},
      {amount:'1½–2 cups',name:'shredded cheddar cheese'},
      {amount:'for topping',name:'sour cream, green onions, crumbled bacon'},
    ],
    steps: [
      'Cook diced bacon in a large pot until crispy. Remove bacon. Reserve 6–8 tbsp grease.',
      'Sauté onion and garlic in bacon grease over medium heat until softened, 5 minutes.',
      'Whisk in flour to make a roux. Cook 1–2 minutes.',
      'Add broth gradually, whisking until smooth. Add potatoes. Simmer 15–20 minutes until potatoes are tender.',
      'Stir in milk or cream and shredded cheddar. Season with salt, pepper, and garlic powder. Top with crumbled bacon, sour cream, and green onions.',
    ],
    notes: 'Bacon grease is the secret flavor base.',
  },
  {
    title: 'French Onion Soup',
    category: 'Soups & Stews', submitted_by: 'Family Collection',
    serves: 'Serves 6', time: '1 hr 30 min',
    ingredients: [
      {amount:'4 lbs',name:'yellow onions, thinly sliced'},
      {amount:'4 tbsp',name:'butter'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'1 tsp each',name:'sugar, salt'},
      {amount:'½ cup',name:'dry white wine or vermouth'},
      {amount:'6 cups',name:'best-quality beef broth'},
      {amount:'1 cup',name:'chicken broth'},
      {amount:'2',name:'bay leaves, fresh thyme sprigs'},
      {amount:'for topping',name:'crusty baguette slices'},
      {amount:'1½ cups',name:'shredded Gruyère or Swiss cheese'},
    ],
    steps: [
      'In a large Dutch oven, melt 4 tbsp butter with 2 tbsp olive oil over medium. Add all onions, 1 tsp salt, and 1 tsp sugar. Cook uncovered, stirring occasionally, 45–60 minutes until deeply golden and caramelized. Do not rush.',
      'Add wine and increase heat. Cook until wine evaporates, about 2 minutes.',
      'Add both broths, bay leaves, and thyme. Bring to a boil, then simmer 20 minutes. Remove bay leaves and thyme. Season with salt and pepper.',
      'Toast baguette slices under the broiler until golden.',
      'Ladle soup into oven-safe bowls. Top with a baguette slice and a generous layer of Gruyère. Broil 3–5 minutes until cheese is bubbling and spotted brown. Serve immediately.',
    ],
    notes: 'Takes time but every minute is worth it.',
  },
  {
    title: 'Crock Pot Beef Stew',
    category: 'Soups & Stews', submitted_by: 'Family Collection',
    serves: 'Serves 6', time: '7–8 hours',
    ingredients: [
      {amount:'2 lbs',name:'stew meat, cut into 1-inch cubes'},
      {amount:'to taste',name:'kosher salt and black pepper'},
      {amount:'1 lb',name:'baby red potatoes, quartered'},
      {amount:'4',name:'carrots, cut into 1-inch pieces'},
      {amount:'1',name:'onion, diced'},
      {amount:'3 cloves',name:'garlic, minced'},
      {amount:'3 cups',name:'beef broth'},
      {amount:'2 tbsp',name:'tomato paste'},
      {amount:'1 tbsp',name:'Worcestershire sauce'},
      {amount:'1 tsp',name:'dried thyme'},
      {amount:'2 tbsp cornstarch + 2 tbsp water',name:'cornstarch slurry'},
    ],
    steps: [
      'Season stew meat with salt and pepper. Brown in olive oil over medium-high in a skillet. Transfer to slow cooker.',
      'Add potatoes, carrots, onion, and garlic.',
      'Whisk together broth, tomato paste, Worcestershire, and thyme. Pour over everything.',
      'Cook on low 7–8 hours or high 4–5 hours until meat and vegetables are tender.',
      'Stir in cornstarch slurry. Cook on high 15–20 more minutes until thickened. Adjust seasoning and serve.',
    ],
    notes: 'Best made a day ahead — the flavors only get better overnight.',
  },
  {
    title: 'Smoked Ribs 3-2-1',
    category: 'Beef & Pork', submitted_by: 'Family Collection',
    serves: 'Serves 4–6', time: '6 hours',
    ingredients: [
      {amount:'2 racks',name:'pork ribs (baby back or spare)'},
      {amount:'4 tbsp',name:'yellow mustard (binder)'},
      {amount:'generously',name:'dry rub: paprika, brown sugar, garlic powder, salt, pepper, cayenne'},
      {amount:'1 cup',name:'apple juice for spritzing and wrapping'},
      {amount:'½ cup',name:'BBQ sauce for wrapping'},
      {amount:'1 cup BBQ sauce + 1½ tbsp each',name:'honey and brown sugar for finishing'},
    ],
    steps: [
      'Remove membrane from back of ribs. Apply mustard as binder. Apply dry rub generously on all sides.',
      'Smoke at 225°F for 3 hours, spritzing with apple juice every 45–60 minutes.',
      'Wrap ribs tightly in foil with BBQ sauce and apple juice. Return to smoker at 225°F for 2 hours.',
      'Unwrap. Mix finishing sauce (BBQ + honey + brown sugar). Brush over ribs. Return to smoker unwrapped for 1 final hour.',
      'Rest 10 minutes before slicing. Serve with extra sauce.',
    ],
    notes: '3 hours smoke, 2 hours wrapped, 1 hour sauced.',
  },
  {
    title: 'Smoked Mac \'n Cheese',
    category: 'Sides', submitted_by: 'Family Collection',
    serves: 'Serves 20+ (scale down as needed)', time: '2–3 hours',
    ingredients: [
      {amount:'2 large blocks',name:'Velveeta cheese, cubed'},
      {amount:'2 lbs',name:'elbow macaroni, cooked and drained'},
      {amount:'1 stick',name:'butter'},
      {amount:'1 pint',name:'heavy whipping cream'},
      {amount:'½ gallon',name:'whole milk'},
      {amount:'to taste',name:'BBQ rub (Meat Church Honey Hog recommended)'},
    ],
    steps: [
      'Cook macaroni per package directions. Drain.',
      'Melt 1 stick butter in a large pot. Add ½ gallon milk and 1 pint cream, bringing to a gentle simmer.',
      'Stir in cubed Velveeta until fully melted and smooth.',
      'Stir in cooked pasta. Season with BBQ rub to taste. Pour into a large aluminum pan.',
      'Smoke at 225–250°F for 1½–2 hours stirring occasionally. Top with more rub or shredded cheddar in the last 30 minutes.',
    ],
    notes: 'A showstopper BBQ side.',
  },
  {
    title: 'Sweet Potato Casserole',
    category: 'Sides', submitted_by: 'Family Collection',
    serves: 'Serves 8', time: '50 min',
    ingredients: [
      {amount:'3 cups',name:'cooked and mashed sweet potatoes'},
      {amount:'1 cup',name:'white sugar'},
      {amount:'½ tsp each',name:'salt, vanilla extract'},
      {amount:'2',name:'eggs, beaten'},
      {amount:'⅓ cup',name:'butter, melted'},
      {amount:'½ cup',name:'evaporated milk or cream'},
      {amount:'Topping: 1 cup',name:'brown sugar, ⅓ cup flour, 1 cup chopped pecans, ⅓ cup melted butter'},
    ],
    steps: [
      'Preheat oven to 350°F. Grease a 9x13 baking dish.',
      'Mix all filling ingredients until smooth. Pour into baking dish.',
      'Combine brown sugar, flour, pecans, and melted butter for the topping. Sprinkle evenly over filling.',
      'Bake 30–35 minutes until topping is golden and filling is set.',
      'Let cool slightly before serving.',
    ],
    notes: 'Might be better than dessert.',
  },
  {
    title: 'Garlic Mashed Potatoes',
    category: 'Sides', submitted_by: 'Family Collection',
    serves: 'Serves 6–8', time: '30 min',
    ingredients: [
      {amount:'3 lbs',name:'red or Yukon gold potatoes'},
      {amount:'4 tbsp',name:'butter'},
      {amount:'8 oz',name:'sour cream'},
      {amount:'½ cup',name:'whole milk'},
      {amount:'1 tbsp',name:'minced garlic'},
      {amount:'1½ tsp',name:'kosher salt, to taste'},
      {amount:'for garnish',name:'fresh chives or parsley'},
    ],
    steps: [
      'Boil potatoes in salted water until fork-tender, about 20 minutes. Drain well.',
      'Return potatoes to the pot. Add 4 tbsp butter, 1 tbsp garlic, 8 oz sour cream, and ½ cup milk.',
      'Mash to desired consistency. Season with salt to taste.',
      'Serve hot garnished with chives or parsley.',
    ],
    notes: null,
  },
  {
    title: 'Fried Rice',
    category: 'Sides', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '20 min',
    ingredients: [
      {amount:'3 tbsp',name:'butter, divided'},
      {amount:'2',name:'eggs, whisked'},
      {amount:'2 medium',name:'carrots, peeled and diced'},
      {amount:'1 small',name:'white onion, diced'},
      {amount:'½ cup',name:'frozen peas'},
      {amount:'3 cloves',name:'garlic, minced'},
      {amount:'4 cups',name:'cooked rice (preferably day-old)'},
      {amount:'3 tbsp',name:'soy sauce'},
      {amount:'2 tsp',name:'sesame oil'},
      {amount:'for garnish',name:'green onions'},
    ],
    steps: [
      'Melt 1 tbsp butter in a large wok or skillet over medium-high. Add eggs and scramble until just cooked. Remove and set aside.',
      'Melt remaining 2 tbsp butter. Add carrots and onion, cook 3 minutes. Add peas and garlic, cook 2 more minutes.',
      'Add rice. Press into pan and let sit 2 minutes without stirring to get slightly crispy. Stir and repeat.',
      'Add 3 tbsp soy sauce and 2 tsp sesame oil. Toss to coat everything evenly.',
      'Stir in scrambled eggs. Season with salt and pepper. Garnish with green onions.',
    ],
    notes: 'Use day-old rice and very high heat.',
  },
  {
    title: 'Spanish Rice',
    category: 'Sides', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '25 min',
    ingredients: [
      {amount:'2 cups',name:'white long-grain rice'},
      {amount:'1 can (8 oz)',name:'tomato sauce'},
      {amount:'2 tbsp',name:'chicken bouillon powder'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'3–4 cups',name:'water'},
    ],
    steps: [
      'Heat a large skillet over medium-high and add 2 tbsp olive oil.',
      'Add dry rice and toast, stirring frequently, 3–4 minutes until lightly golden.',
      'Pour in tomato sauce, chicken bouillon, and enough water to cover rice by ½ inch.',
      'Stir, bring to a boil, then reduce heat to low, cover, and cook 18–20 minutes until water is absorbed.',
      'Fluff with a fork and serve.',
    ],
    notes: null,
  },
  {
    title: 'Potato Salad',
    category: 'Sides', submitted_by: 'Family Collection',
    serves: 'Serves 8', time: '30 min + 4–6 hr chill',
    ingredients: [
      {amount:'as many as needed',name:'Yukon gold potatoes'},
      {amount:'a splash',name:'white vinegar (added while potatoes are warm)'},
      {amount:'3',name:'hard-boiled eggs, chopped'},
      {amount:'as needed',name:'celery chopped, green onion sliced'},
      {amount:'1½ tbsp',name:'Miracle Whip (the secret ingredient)'},
      {amount:'to taste',name:'additional mayo, salt, pepper, garlic powder'},
      {amount:'for color',name:'paprika'},
    ],
    steps: [
      'Boil potatoes in salted water until just tender. Drain and cool slightly — not fully.',
      'While still warm, cut into bite-size chunks and splash with white vinegar. Toss gently.',
      'Add chopped eggs, celery, and green onion.',
      'Stir in 1½ tbsp Miracle Whip and additional mayo to reach desired creaminess. Season with salt, pepper, and garlic powder.',
      'Refrigerate at least 4–6 hours or overnight. Sprinkle with paprika before serving.',
    ],
    notes: 'Miracle Whip is the secret. Must be made ahead.',
  },
  {
    title: 'Cheesy Smashed Potatoes',
    category: 'Sides', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '35 min',
    ingredients: [
      {amount:'1 lb',name:'mini potatoes'},
      {amount:'as needed',name:'olive oil'},
      {amount:'to taste',name:'garlic salt, Italian seasoning'},
      {amount:'generous amount',name:'shredded Parmesan and mozzarella'},
    ],
    steps: [
      'Boil potatoes in salted water until tender, about 15 minutes. Drain.',
      'Preheat oven to 425°F. Arrange potatoes on an oiled baking sheet.',
      'Cut each potato in half and score a criss-cross on the cut side. Smash each potato flat.',
      'Drizzle with olive oil, season, then top generously with Parmesan and mozzarella.',
      'Roast 15–20 minutes until crispy and cheese is golden.',
    ],
    notes: null,
  },
  {
    title: 'Buffalo Chicken Dip',
    category: 'Appetizers & Snacks', submitted_by: 'Family Collection',
    serves: 'Serves 8–10', time: '25 min',
    ingredients: [
      {amount:'2 cups',name:'shredded cooked chicken'},
      {amount:'8 oz',name:'cream cheese, softened'},
      {amount:'½+ cup',name:"Frank's RedHot Original Hot Sauce"},
      {amount:'8 oz',name:'shredded cheddar or blend cheese'},
      {amount:'½ cup',name:'ranch dressing'},
    ],
    steps: [
      'Preheat oven to 350°F.',
      'Mix all ingredients together in a large bowl until well combined.',
      'Spread into a shallow 1-quart baking dish.',
      'Bake 20 minutes until heated through and bubbly.',
      'Serve hot with tortilla chips, celery sticks, or toasted baguette slices.',
    ],
    notes: 'Goes fast — make two.',
  },
  {
    title: 'Potato Skins',
    category: 'Appetizers & Snacks', submitted_by: 'Family Collection',
    serves: 'Serves 4–6', time: '1 hr 15 min',
    ingredients: [
      {amount:'6 medium',name:'russet potatoes (3 lbs)'},
      {amount:'as needed',name:'extra-virgin olive oil, kosher salt and pepper'},
      {amount:'6 slices',name:'bacon, cooked and crumbled'},
      {amount:'4 oz',name:'grated cheddar cheese'},
      {amount:'½ cup',name:'sour cream'},
      {amount:'2',name:'green onions, thinly sliced'},
    ],
    steps: [
      'Preheat oven to 400°F. Rub potatoes with olive oil and salt. Bake 50–60 minutes until tender. Cool slightly.',
      'Halve potatoes lengthwise. Scoop out most of the flesh, leaving about ¼ inch inside.',
      'Brush skins inside and out with olive oil. Season with salt and pepper. Return to oven 10 minutes until crispy.',
      'Fill each skin with cheddar and crumbled bacon. Bake another 5 minutes until cheese is melted.',
      'Top with sour cream and green onions. Serve immediately.',
    ],
    notes: 'Best game-day snack going.',
  },
  {
    title: 'Salsa',
    category: 'Sauces & Dips', submitted_by: 'Family Collection',
    serves: 'Makes ~2 cups', time: '10 min',
    ingredients: [
      {amount:'1 can',name:'diced tomatoes'},
      {amount:'½',name:'onion, diced'},
      {amount:'1 tbsp',name:'minced garlic'},
      {amount:'¼ cup',name:'diced jalapeño'},
      {amount:'1 tbsp',name:'lime juice'},
      {amount:'1 tbsp',name:'dried cilantro (fresh preferred)'},
      {amount:'¼ tsp each',name:'salt, sugar, cumin'},
      {amount:'to taste',name:'red pepper flakes'},
    ],
    steps: [
      'Combine all ingredients in a blender or food processor.',
      'Pulse to desired consistency — chunky or smooth.',
      'Taste and adjust salt, lime, and heat.',
      'Refrigerate at least 30 minutes before serving.',
    ],
    notes: 'Fresh cilantro is best.',
  },
  {
    title: 'Tzatziki Sauce',
    category: 'Sauces & Dips', submitted_by: 'Family Collection',
    serves: 'Makes ~1½ cups', time: '15 min + 30 min chill',
    ingredients: [
      {amount:'¾',name:'English cucumber, partially peeled'},
      {amount:'1 tsp',name:'kosher salt, divided'},
      {amount:'4–5',name:'garlic cloves, finely grated (start with 1–2 for milder)'},
      {amount:'1 cup',name:'full-fat Greek yogurt'},
      {amount:'2 tbsp',name:'extra-virgin olive oil'},
      {amount:'1 tbsp',name:'fresh lemon juice'},
      {amount:'2 tbsp',name:'fresh dill (or 1 tsp dried)'},
    ],
    steps: [
      'Grate cucumber. Place in a strainer, toss with ½ tsp salt, and let drain 10 minutes. Squeeze out all excess liquid.',
      'Combine strained cucumber, yogurt, garlic, olive oil, lemon juice, and dill in a bowl.',
      'Season with remaining salt and pepper. Stir well.',
      'Refrigerate at least 30 minutes before serving.',
    ],
    notes: 'The real deal. Start with less garlic if you prefer milder.',
  },
  {
    title: 'French Toast Casserole',
    category: 'Breakfast', submitted_by: 'Family Collection',
    serves: 'Serves 8', time: '10 min + overnight + 50 min bake',
    ingredients: [
      {amount:'1 cup',name:'brown sugar'},
      {amount:'½ cup',name:'unsalted butter'},
      {amount:'1 loaf (8 oz)',name:'crusty French bread, cut into bite-sized pieces'},
      {amount:'2 cups',name:'milk'},
      {amount:'6',name:'large eggs'},
      {amount:'1 tsp each',name:'vanilla extract, cinnamon'},
      {amount:'¼ tsp',name:'nutmeg'},
      {amount:'for serving',name:'powdered sugar and maple syrup'},
    ],
    steps: [
      'Melt butter and brown sugar in a saucepan until combined. Pour into a greased 9x13 baking dish.',
      'Layer bread pieces over the butter-sugar mixture.',
      'Whisk together eggs, milk, vanilla, cinnamon, nutmeg, and a pinch of salt. Pour evenly over bread.',
      'Cover and refrigerate overnight (or at least 4 hours).',
      'Bake at 350°F for 45–55 minutes until puffed and golden. Serve immediately with powdered sugar and maple syrup.',
    ],
    notes: 'Make the night before for an easy morning.',
  },
  {
    title: 'Fluffy Pancakes',
    category: 'Breakfast', submitted_by: 'Family Collection',
    serves: 'Makes ~8 pancakes', time: '20 min',
    ingredients: [
      {amount:'¾ cup',name:'milk'},
      {amount:'2 tbsp',name:'white vinegar'},
      {amount:'1 cup',name:'all-purpose flour'},
      {amount:'2 tbsp',name:'white sugar'},
      {amount:'1 tsp',name:'baking powder'},
      {amount:'½ tsp each',name:'baking soda, salt'},
      {amount:'1',name:'egg'},
      {amount:'2 tbsp',name:'butter, melted'},
      {amount:'for serving',name:'butter and maple syrup'},
    ],
    steps: [
      'Combine ¾ cup milk and 2 tbsp white vinegar. Let sit 5 minutes to curdle into DIY buttermilk.',
      'In a large bowl, whisk 1 cup flour, 2 tbsp sugar, 1 tsp baking powder, ½ tsp baking soda, and ½ tsp salt.',
      'Beat egg and 2 tbsp melted butter into the milk mixture. Pour into dry ingredients and stir just until combined — lumps are okay.',
      'Let batter rest 5 minutes.',
      'Heat a greased griddle over medium. Pour ¼ cup batter per pancake. Cook until bubbles form and edges look set, 2–3 minutes. Flip and cook 1–2 more minutes. Serve hot.',
    ],
    notes: null,
  },
  {
    title: 'Chocolate Chip Cookies',
    category: 'Desserts', submitted_by: 'Family Collection',
    serves: 'Makes ~36 cookies', time: '24–72 hr chill + 15 min bake',
    ingredients: [
      {amount:'17 oz',name:'all-purpose flour (or cake flour + bread flour blend)'},
      {amount:'1¼ tsp',name:'baking soda'},
      {amount:'1½ tsp each',name:'baking powder, coarse salt'},
      {amount:'2½ sticks (1¼ cups)',name:'unsalted butter, room temperature'},
      {amount:'1¼ cups',name:'light brown sugar, packed'},
      {amount:'1 cup plus 2 tbsp',name:'granulated sugar'},
      {amount:'2',name:'large eggs'},
      {amount:'2 tsp',name:'vanilla extract'},
      {amount:'1¼ lbs',name:'best-quality chocolate chips or discs'},
    ],
    steps: [
      'Sift together flour, baking soda, baking powder, and salt. Set aside.',
      'Beat butter and both sugars together on medium speed for 5 minutes until light and fluffy.',
      'Add eggs one at a time, then vanilla. Reduce speed to low and add dry ingredients until just combined. Fold in chocolate chips.',
      'Refrigerate dough for at least 24 hours (up to 72 hours — this is the secret).',
      'Preheat oven to 350°F. Scoop chilled dough in 3½-oz portions onto baking sheets. Bake 12–14 minutes until golden brown but still slightly soft in center. Cool on sheets 10 minutes.',
    ],
    notes: 'The long chill is non-negotiable.',
  },
  {
    title: 'Cherry Delight',
    category: 'Desserts', submitted_by: 'Family Collection',
    serves: 'Serves 12', time: '20 min + 2 hr chill',
    ingredients: [
      {amount:'1½ cups',name:'graham cracker crumbs'},
      {amount:'3 tbsp',name:'granulated sugar'},
      {amount:'7 tbsp',name:'unsalted butter, melted'},
      {amount:'8 oz',name:'cream cheese, softened'},
      {amount:'1 cup',name:'powdered sugar'},
      {amount:'1 tub (8 oz)',name:'Cool Whip'},
      {amount:'1 can',name:'cherry pie filling'},
    ],
    steps: [
      'Combine graham cracker crumbs, 3 tbsp sugar, and melted butter. Press firmly into bottom of a 9x13 pan. Chill 15 minutes.',
      'Beat cream cheese and 1 cup powdered sugar until smooth. Fold in Cool Whip.',
      'Spread cream cheese mixture evenly over the crust.',
      'Spoon cherry pie filling over the top.',
      'Refrigerate at least 2 hours before serving. Cut into squares.',
    ],
    notes: null,
  },
  {
    title: 'Mtn Dew Hillbilly Dumplins',
    category: 'Desserts', submitted_by: 'Family Collection',
    serves: 'Serves 8–10', time: '50 min',
    ingredients: [
      {amount:'2 cans',name:'crescent rolls'},
      {amount:'2 sticks',name:'butter'},
      {amount:'2',name:'Granny Smith apples, peeled, cored, each cut into 8 slices'},
      {amount:'to taste',name:'cinnamon'},
      {amount:'1½ cups',name:'light brown sugar'},
      {amount:'12 oz',name:'Mountain Dew'},
    ],
    steps: [
      'Preheat oven to 350°F. Grease a 9x13 baking dish.',
      'Wrap each apple slice in a crescent roll triangle. Place seam-side down in the baking dish.',
      'In a saucepan, melt 2 sticks butter with 1½ cups brown sugar until dissolved. Pour over the dumplings.',
      'Pour Mountain Dew around the edges (not directly on top).',
      'Sprinkle cinnamon over everything. Bake 35–45 minutes until golden brown and bubbly. Serve warm with vanilla ice cream.',
    ],
    notes: 'Sounds wild, tastes incredible.',
  },
  {
    title: 'Lemon Meringue Pie — Graham Cracker Crust',
    category: 'Desserts', submitted_by: 'Family Collection',
    serves: 'Serves 8', time: '1 hr + chill',
    ingredients: [
      {amount:'1½ cups',name:'graham cracker crumbs'},
      {amount:'3 tbsp',name:'sugar'},
      {amount:'6 tbsp',name:'butter, melted'},
      {amount:'1½ cups',name:'sugar (for filling)'},
      {amount:'3 tbsp each',name:'cornstarch, all-purpose flour'},
      {amount:'1½ cups',name:'hot water'},
      {amount:'3',name:'egg yolks, slightly beaten'},
      {amount:'2 tbsp',name:'butter'},
      {amount:'½ tsp',name:'grated lemon zest'},
      {amount:'⅓ cup',name:'fresh lemon juice'},
      {amount:'3',name:'egg whites'},
      {amount:'¼ tsp',name:'cream of tartar'},
      {amount:'6 tbsp',name:'sugar (for meringue)'},
    ],
    steps: [
      'Crust: combine crumbs, 3 tbsp sugar, and melted butter. Press into a 9-inch pie plate. Bake at 350°F for 8 minutes. Cool.',
      'Filling: Mix sugar, cornstarch, flour, and salt in a saucepan. Gradually stir in 1½ cups hot water. Cook and stir over medium-high until thickened and bubbly. Cook 2 more minutes. Remove from heat.',
      'Stir a small amount of hot filling into beaten egg yolks, then return all to pan. Bring to a boil. Stir in 2 tbsp butter, lemon zest, and ⅓ cup lemon juice. Pour hot filling into crust.',
      'Meringue: Beat egg whites with cream of tartar to soft peaks. Gradually add 6 tbsp sugar, beating to stiff glossy peaks. Beat in ½ tsp vanilla.',
      'Spread meringue over hot filling, sealing edges to crust. Bake at 350°F for 12–15 minutes until golden. Cool completely before serving.',
    ],
    notes: null,
  },
  {
    title: 'Elizondo Chicken',
    category: 'Chicken', submitted_by: 'Family Signature Recipe',
    serves: 'Serves 4', time: '30 min',
    ingredients: [
      {amount:'½ stick',name:'butter'},
      {amount:'to taste',name:'garlic, minced from jar'},
      {amount:'~2 lbs',name:'chicken breast, cut into long skinny strips'},
      {amount:'a splash',name:'Jugo (Mexican soy sauce)'},
      {amount:'a splash',name:'tequila'},
      {amount:'to taste',name:'garlic salt, ground pepper, Himalayan pink salt'},
    ],
    steps: [
      'Cut chicken into long, thin strips.',
      'Season chicken with garlic salt, ground pepper, and pink salt. Marinate in a splash of tequila and Jugo for 30 minutes if time allows.',
      'Melt ½ stick butter in a large skillet over medium-high heat. Add minced garlic and cook 30 seconds.',
      'Add chicken strips and cook, stirring occasionally, until cooked through and slightly caramelized, 6–8 minutes.',
      'Serve over rice, in tacos, or alongside grilled vegetables.',
    ],
    notes: 'A family signature recipe. Named after the Elizondo family.',
  },
  {
    title: 'Fish Tacos with Mango Salsa',
    category: 'Seafood', submitted_by: "Aunt Chrissy's Favorite",
    serves: 'Serves 4', time: '25 min',
    ingredients: [
      {amount:'1½ lbs',name:'tilapia or other mild white fish'},
      {amount:'1 tsp each',name:'cumin, paprika, garlic powder'},
      {amount:'to taste',name:'salt and pepper'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'for serving',name:'flour or corn tortillas, lime wedges'},
      {amount:'1 ripe',name:'mango, peeled and diced'},
      {amount:'½',name:'red onion, finely diced'},
      {amount:'1',name:'jalapeño, seeded and minced'},
      {amount:'1',name:'lime, juiced'},
      {amount:'2 tbsp',name:'fresh cilantro, chopped'},
    ],
    steps: [
      'Combine all mango salsa ingredients. Refrigerate 30 minutes.',
      'Season fish with cumin, paprika, garlic powder, salt, and pepper.',
      'Heat 2 tbsp olive oil in a skillet over medium-high. Cook fish 3–4 minutes per side until golden and flakes easily.',
      'Break fish into large chunks. Warm tortillas.',
      'Build tacos: fish, mango salsa, a squeeze of lime. Serve immediately.',
    ],
    notes: 'Aunt Chrissy\'s favorite. Use tilapia from Kroger.',
  },
  {
    title: 'Chicken Marsala',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '35 min',
    ingredients: [
      {amount:'2 large',name:'chicken breasts, halved horizontally into thin cutlets'},
      {amount:'½ tsp each',name:'kosher salt, black pepper'},
      {amount:'¼ cup',name:'plain flour for dredging'},
      {amount:'2 tbsp each',name:'olive oil, butter'},
      {amount:'8 oz',name:'cremini mushrooms, sliced'},
      {amount:'3',name:'garlic cloves, minced'},
      {amount:'¾ cup',name:'dry Marsala wine'},
      {amount:'½ cup',name:'chicken stock'},
      {amount:'¼ cup',name:'heavy cream'},
      {amount:'for garnish',name:'fresh thyme and parsley'},
    ],
    steps: [
      'Season chicken with ½ tsp each salt and pepper. Dredge in flour.',
      'Heat 2 tbsp olive oil in a skillet over medium-high. Cook chicken 3–4 min per side until golden. Transfer to a plate.',
      'In the same pan, melt 2 tbsp butter. Add mushrooms, cook 4–5 min. Add garlic, cook 1 min.',
      'Pour in ¾ cup Marsala wine and let bubble 1 minute. Add ½ cup stock and ¼ cup cream. Simmer 3–4 min until slightly thickened.',
      'Return chicken to pan. Simmer 3 min. Garnish with thyme and parsley. Serve over mashed potatoes or pasta.',
    ],
    notes: null,
  },
  {
    title: 'Crack Chicken Casserole',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 6', time: '1 hour',
    ingredients: [
      {amount:'3 cups',name:'cooked chicken, shredded'},
      {amount:'8 oz',name:'cream cheese, softened'},
      {amount:'1 packet',name:'ranch seasoning'},
      {amount:'1 cup each',name:'shredded cheddar, shredded mozzarella'},
      {amount:'½ cup',name:'cooked bacon, crumbled'},
      {amount:'½ cup',name:'sour cream'},
      {amount:'1 cup',name:'chicken broth'},
      {amount:'8 oz',name:'penne or rotini pasta, cooked'},
      {amount:'for topping',name:'extra cheese'},
    ],
    steps: [
      'Preheat oven to 375°F. Grease a 9x13 baking dish.',
      'Mix cream cheese, ranch seasoning, sour cream, and 1 cup chicken broth until smooth.',
      'Stir in chicken, cooked pasta, cheddar, mozzarella, and bacon. Season with salt, pepper, and garlic powder.',
      'Pour into the prepared dish. Top with additional cheese.',
      'Bake 25–30 minutes until bubbly and cheese is golden. Let rest 5 minutes before serving.',
    ],
    notes: 'Layers upon layers of deep, addictive flavor.',
  },
  {
    title: 'Slow Cooker Garlic Parmesan Chicken & Potatoes',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 4–6', time: '6–7 hours',
    ingredients: [
      {amount:'2 lbs',name:'bone-in, skin-on chicken thighs or breasts'},
      {amount:'to taste',name:'kosher salt and black pepper'},
      {amount:'1 lb',name:'baby red potatoes, quartered'},
      {amount:'2 tbsp each',name:'olive oil, butter'},
      {amount:'6',name:'garlic cloves, minced'},
      {amount:'1 cup',name:'chicken broth'},
      {amount:'1 tsp',name:'Italian seasoning'},
      {amount:'½ cup',name:'grated Parmesan cheese'},
      {amount:'2 tbsp',name:'fresh parsley, chopped'},
    ],
    steps: [
      'Heat 2 tbsp olive oil in a skillet. Season chicken with salt and pepper. Brown skin-side down 4–5 minutes until golden. Transfer to slow cooker.',
      'Add quartered potatoes around the chicken.',
      'Melt 2 tbsp butter in the same skillet, sauté 6 minced garlic cloves 30 seconds. Add 1 cup chicken broth and 1 tsp Italian seasoning. Pour over chicken and potatoes.',
      'Cook on low 6–7 hours or high 3–4 hours until chicken is cooked through and potatoes are tender.',
      'Sprinkle with Parmesan and parsley. Serve with cooking juices spooned over.',
    ],
    notes: null,
  },
  {
    title: 'Baked Tortellini',
    category: 'Pasta', submitted_by: 'Family Collection',
    serves: 'Serves 6', time: '45 min',
    ingredients: [
      {amount:'1 lb',name:'ground beef'},
      {amount:'1 jar (28 oz)',name:'spaghetti sauce'},
      {amount:'1 jar (15 oz)',name:'Alfredo sauce'},
      {amount:'a splash',name:'heavy cream'},
      {amount:'24 oz',name:'cheese tortellini, cooked'},
      {amount:'8+ oz',name:'shredded mozzarella'},
      {amount:'to taste',name:'garlic salt, Italian seasoning, pepper'},
    ],
    steps: [
      'Preheat oven to 375°F. Brown ground beef, drain fat. Season with garlic salt, Italian seasoning, and pepper.',
      'Stir in spaghetti sauce and a splash of heavy cream. Simmer 5 minutes.',
      'Cook tortellini per package directions. Drain.',
      'Mix tortellini and Alfredo sauce together. Pour into a greased 9x13 baking dish. Spoon meat sauce over the top.',
      'Cover with shredded mozzarella. Bake 20–25 minutes until bubbly and cheese is golden. Let rest 5 minutes before serving.',
    ],
    notes: 'Two-sauce approach makes it extra rich.',
  },
  {
    title: 'Cajun Chicken Alfredo',
    category: 'Pasta', submitted_by: 'Family Collection',
    serves: 'Serves 4', time: '35 min',
    ingredients: [
      {amount:'1½ lbs',name:'chicken breast'},
      {amount:'2 tbsp',name:'Cajun seasoning'},
      {amount:'½ stick',name:'butter'},
      {amount:'1 clove',name:'garlic, minced'},
      {amount:'1',name:'Andouille sausage, sliced'},
      {amount:'4 cups',name:'chicken broth'},
      {amount:'3 cups',name:'heavy cream'},
      {amount:'12 oz',name:'fettuccine or penne pasta, cooked'},
      {amount:'for serving',name:'Parmesan cheese, parsley'},
    ],
    steps: [
      'Season chicken with 2 tbsp Cajun seasoning. Sear in ½ stick butter over medium-high heat, 4–5 minutes per side. Remove and slice.',
      'In the same pan, sauté Andouille sausage until browned. Add garlic and cook 30 seconds.',
      'Pour in 4 cups chicken broth. Simmer until reduced by half. Add 3 cups heavy cream and bring to a simmer.',
      'Cook sauce until thickened, stirring occasionally, about 10 minutes. Season with additional Cajun seasoning to taste.',
      'Stir in cooked pasta and sliced chicken. Toss to coat. Serve topped with Parmesan and parsley.',
    ],
    notes: null,
  },
  {
    title: 'Crock Pot Baby Back Ribs',
    category: 'Beef & Pork', submitted_by: 'Family Collection',
    serves: 'Serves 4–6', time: '6–8 hours + 10 min broil',
    ingredients: [
      {amount:'2 slabs',name:'baby back pork ribs'},
      {amount:'to coat',name:'dry rub: salt, pepper, paprika, garlic powder, brown sugar'},
      {amount:'½ cup',name:'apple juice or apple cider vinegar'},
      {amount:'1–2 cups',name:'BBQ sauce of choice'},
    ],
    steps: [
      'Remove membrane from back of each rack. Apply dry rub generously on all sides.',
      'Cut racks in half to fit. Stand ribs upright around the inside of the slow cooker.',
      'Pour apple juice into the bottom. Cook on low 6–8 hours or high 4–5 hours.',
      'Carefully remove ribs to a foil-lined baking sheet. Brush with BBQ sauce.',
      'Broil 5–7 minutes until sauce caramelizes and edges are slightly charred. Serve with extra sauce.',
    ],
    notes: null,
  },
  {
    title: 'Slow Cooker Prime Rib',
    category: 'Beef & Pork', submitted_by: 'Family Collection',
    serves: 'Serves 6', time: '12 hr chill + 6 hr cook',
    ingredients: [
      {amount:'4–6 lbs',name:'prime rib roast (bone-in or boneless)'},
      {amount:'3 tbsp',name:'kosher salt'},
      {amount:'2 tbsp each',name:'black pepper, garlic powder'},
      {amount:'1 tbsp each',name:'fresh rosemary and thyme, chopped'},
      {amount:'2 tbsp',name:'olive oil'},
      {amount:'1 cup',name:'beef broth'},
      {amount:'for serving',name:'horseradish cream and au jus'},
    ],
    steps: [
      'Mix salt, pepper, garlic powder, rosemary, and thyme. Rub all over the roast. Refrigerate uncovered 12 hours or overnight.',
      'Sear roast in a very hot skillet with olive oil on all sides until deeply browned.',
      'Place in slow cooker fat-side up. Pour broth into the bottom.',
      'Cook on low 4–6 hours until internal temp reaches 120–125°F for medium-rare.',
      'Rest 20–30 minutes before slicing. Serve with horseradish cream and pan juices for au jus.',
    ],
    notes: 'An impressive holiday centerpiece with minimal hands-on effort.',
  },
  {
    title: 'Steak Fajitas',
    category: 'Beef & Pork', submitted_by: 'Family Collection',
    serves: 'Serves 4–6', time: '30 min + marinate',
    ingredients: [
      {amount:'~2 lbs',name:'flank steak (2 steaks)'},
      {amount:'a splash',name:'liquid smoke'},
      {amount:'to coat',name:'teriyaki or Caribbean jerk marinade'},
      {amount:'2–3',name:'limes, juiced'},
      {amount:'3–4',name:'sweet bell peppers (yellow, red, orange), sliced'},
      {amount:'1',name:'Vidalia onion, sliced'},
      {amount:'as needed',name:'olive oil, salt, pepper'},
      {amount:'for serving',name:'flour tortillas, sour cream, guacamole, cheese, lime wedges'},
    ],
    steps: [
      'Tenderize steak with a meat mallet. Score surface in a crosshatch. Coat in liquid smoke, marinade, and lime juice. Marinate 1–4 hours.',
      'Grill or sear steak over very high heat, 3–4 minutes per side for medium-rare. Rest 5–10 minutes. Slice thinly against the grain.',
      'In a cast iron skillet, sauté peppers and onion in olive oil over medium-high until caramelized, 10–15 minutes. Season with salt and pepper.',
      'Warm tortillas.',
      'Serve sliced steak in tortillas with peppers, onions, lime wedges, and your favorite toppings.',
    ],
    notes: null,
  },
  {
    title: 'Chicken Pot Pie',
    category: 'Chicken', submitted_by: 'Family Collection',
    serves: 'Serves 6', time: '1 hr 20 min',
    ingredients: [
      {amount:'½ package (17.3 oz)',name:'Pepperidge Farm Puff Pastry Sheets'},
      {amount:'1 egg + 1 tbsp water',name:'egg wash'},
      {amount:'6 cups',name:'cooked chicken, cubed or shredded'},
      {amount:'2 cans',name:'cream of chicken soup'},
      {amount:'1 cup',name:'chicken broth'},
      {amount:'1 bag',name:'frozen mixed vegetables'},
      {amount:'½ cup',name:'sour cream'},
      {amount:'1 tsp each',name:'garlic powder, Italian seasoning'},
    ],
    steps: [
      'Preheat oven to 400°F. Thaw puff pastry per package instructions.',
      'Mix chicken, cream of chicken soup, broth, vegetables, sour cream, garlic powder, Italian seasoning, salt, and pepper in a large bowl.',
      'Pour filling into a greased 9x13 baking dish.',
      'Unfold puff pastry and lay over the filling, pressing edges to seal. Score top with a knife. Brush with egg wash.',
      'Bake 30–35 minutes until pastry is golden brown and puffed. Cool 10 minutes before serving.',
    ],
    notes: null,
  },
]

export default async function handler(req, res) {
  // Simple security — only allow POST with the right secret
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }
  if (req.headers['x-seed-secret'] !== process.env.SEED_SECRET) {
    return res.status(401).json({ error: 'Unauthorized' })
  }

  try {
    // Clear existing seeded recipes first
    await supabase.from('recipes').delete().eq('submitted_by', 'Family Collection')
    await supabase.from('recipes').delete().eq('submitted_by', "Chrissy's Favorite")
    await supabase.from('recipes').delete().eq('submitted_by', 'Family Signature Recipe')
    await supabase.from('recipes').delete().eq('submitted_by', "Aunt Chrissy's Favorite")

    // Insert in batches of 10
    const batchSize = 10
    let inserted = 0
    for (let i = 0; i < recipes.length; i += batchSize) {
      const batch = recipes.slice(i, i + batchSize)
      const { data, error } = await supabase.from('recipes').insert(batch).select()
      if (error) throw error
      inserted += data.length
    }

    return res.status(200).json({ success: true, inserted })
  } catch (err) {
    return res.status(500).json({ error: err.message })
  }
}
